# Generated by Django 5.1.4 on 2026-05-12 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("KPI", "KPI Card"),
                            ("LINE", "Line Chart"),
                            ("BAR", "Bar Chart"),
                            ("PIE", "Pie Chart"),
                            ("TABLE", "Table"),
                            ("GAUGE", "Gauge"),
                        ],
                        max_length=10,
                    ),
                ),
                ("metric_key", models.CharField(max_length=60)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("position", models.IntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboard_widgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="SavedReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("OPD_VOLUME", "OPD Volume"),
                            ("IPD_OCCUPANCY", "IPD Occupancy"),
                            ("OT_UTILIZATION", "OT Utilization"),
                            ("REVENUE_MONTHLY", "Revenue (Monthly)"),
                            ("REVENUE_DEPT", "Revenue (Department)"),
                            ("AR_AGING", "Accounts Receivable Aging"),
                            ("PHARMACY_TURN", "Pharmacy Turnover"),
                            ("LAB_TURNOVER", "Lab Turnover"),
                            ("BLOOD_INVENTORY", "Blood Bank Inventory"),
                            ("DIAGNOSES_TOP", "Top Diagnoses"),
                            ("ASSET_DEPREC", "Asset Depreciation"),
                            ("HR_HEADCOUNT", "HR Headcount"),
                            ("ATTENDANCE_SUM", "Attendance Summary"),
                            ("INSURANCE_CLAIM", "Insurance Claim Summary"),
                            ("COMPLAINTS_SLA", "Complaints SLA Performance"),
                            ("CUSTOM", "Custom SQL"),
                        ],
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("is_pinned", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_reports",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_pinned", "name"],
            },
        ),
        migrations.CreateModel(
            name="ReportRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("OPD_VOLUME", "OPD Volume"),
                            ("IPD_OCCUPANCY", "IPD Occupancy"),
                            ("OT_UTILIZATION", "OT Utilization"),
                            ("REVENUE_MONTHLY", "Revenue (Monthly)"),
                            ("REVENUE_DEPT", "Revenue (Department)"),
                            ("AR_AGING", "Accounts Receivable Aging"),
                            ("PHARMACY_TURN", "Pharmacy Turnover"),
                            ("LAB_TURNOVER", "Lab Turnover"),
                            ("BLOOD_INVENTORY", "Blood Bank Inventory"),
                            ("DIAGNOSES_TOP", "Top Diagnoses"),
                            ("ASSET_DEPREC", "Asset Depreciation"),
                            ("HR_HEADCOUNT", "HR Headcount"),
                            ("ATTENDANCE_SUM", "Attendance Summary"),
                            ("INSURANCE_CLAIM", "Insurance Claim Summary"),
                            ("COMPLAINTS_SLA", "Complaints SLA Performance"),
                            ("CUSTOM", "Custom SQL"),
                        ],
                        max_length=20,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "Running"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="RUNNING",
                        max_length=10,
                    ),
                ),
                ("row_count", models.IntegerField(default=0)),
                ("runtime_ms", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "run_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="analytics.savedreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.AddIndex(
            model_name="savedreport",
            index=models.Index(
                fields=["hospital", "report_type"],
                name="analytics_s_hospita_f75cc9_idx",
            ),
        ),
    ]
