# Generated by Django 5.1.4 on 2026-05-11 11:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("department", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_code",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated, e.g. ASSET-20260508-0001",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "serial_number",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=80
                    ),
                ),
                (
                    "model_number",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("barcode", models.CharField(blank=True, default="", max_length=80)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "purchase_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "depreciation_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Annual depreciation %",
                        max_digits=5,
                    ),
                ),
                (
                    "salvage_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=14
                    ),
                ),
                ("useful_life_years", models.PositiveIntegerField(default=10)),
                ("warranty_start_date", models.DateField(blank=True, null=True)),
                ("warranty_end_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, default="", max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active / In Use"),
                            ("UNDER_REPAIR", "Under Repair"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("IDLE", "Idle / Reserve"),
                            ("DISPOSED", "Disposed"),
                            ("LOST", "Lost / Stolen"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=15,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("EXCELLENT", "Excellent"),
                            ("GOOD", "Good"),
                            ("FAIR", "Fair"),
                            ("POOR", "Poor"),
                            ("NON_FUNCTIONAL", "Non-functional"),
                        ],
                        default="GOOD",
                        max_length=15,
                    ),
                ),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                (
                    "next_maintenance_date",
                    models.DateField(blank=True, db_index=True, null=True),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "custodian",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="custodian_of_assets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assets",
                        to="department.department",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["asset_code"],
            },
        ),
        migrations.CreateModel(
            name="AMC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_number", models.CharField(db_index=True, max_length=50)),
                ("vendor_name", models.CharField(max_length=200)),
                (
                    "vendor_contact",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "contract_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("coverage_details", models.TextField(blank=True, default="")),
                ("excluded_items", models.TextField(blank=True, default="")),
                (
                    "visit_frequency",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 'Quarterly', 'Monthly', '4 visits/year'",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("RENEWED", "Renewed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amcs",
                        to="assets.asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "AMC",
                "verbose_name_plural": "AMCs",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(max_length=120)),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("MEDICAL_EQUIP", "Medical Equipment"),
                            ("IT_HARDWARE", "IT Hardware"),
                            ("FURNITURE", "Furniture & Fixtures"),
                            ("VEHICLE", "Vehicle"),
                            ("BUILDING", "Building / Infrastructure"),
                            ("OFFICE_EQUIP", "Office Equipment"),
                            ("LAB_EQUIP", "Laboratory Equipment"),
                            ("KITCHEN_EQUIP", "Kitchen Equipment"),
                            ("OTHER", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "default_depreciation_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("10.00"),
                        help_text="Annual depreciation %, used if not overridden on asset",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asset_categories",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Asset Categories",
                "ordering": ["category_type", "code"],
                "unique_together": {("hospital", "code")},
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="assets.assetcategory",
            ),
        ),
        migrations.CreateModel(
            name="AssetDisposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disposal_date", models.DateField()),
                (
                    "disposal_type",
                    models.CharField(
                        choices=[
                            ("SCRAP", "Scrapped"),
                            ("SOLD", "Sold"),
                            ("DONATED", "Donated"),
                            ("LOST", "Lost"),
                            ("DAMAGED", "Damaged Beyond Repair"),
                            ("TRANSFERRED", "Transferred (External)"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "sale_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("recipient", models.CharField(blank=True, default="", max_length=200)),
                ("reason", models.TextField()),
                (
                    "certificate_reference",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_disposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disposal",
                        to="assets.asset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetMaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "maintenance_type",
                    models.CharField(
                        choices=[
                            ("PREVENTIVE", "Preventive Maintenance"),
                            ("BREAKDOWN", "Breakdown / Repair"),
                            ("CALIBRATION", "Calibration"),
                            ("INSPECTION", "Inspection"),
                            ("WARRANTY", "Warranty Service"),
                            ("UPGRADE", "Upgrade / Modification"),
                        ],
                        default="PREVENTIVE",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=12,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("description", models.CharField(max_length=300)),
                ("work_performed", models.TextField(blank=True, default="")),
                ("parts_replaced", models.TextField(blank=True, default="")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "vendor_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "technician_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("next_due_date", models.DateField(blank=True, null=True)),
                ("is_under_amc", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_logs",
                        to="assets.asset",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["status", "category"], name="assets_asse_status_35fdfb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(
                fields=["department"], name="assets_asse_departm_eda949_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="assetmaintenancelog",
            index=models.Index(
                fields=["status", "scheduled_date"],
                name="assets_asse_status_153f7f_idx",
            ),
        ),
    ]
