# Generated by Django 5.1.4 on 2026-05-11 06:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("department", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cylinder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        db_index=True,
                        help_text="Manufacturer serial number",
                        max_length=40,
                        unique=True,
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="QR/barcode label for scanner workflow",
                        max_length=60,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available (Full)"),
                            ("PARTIAL", "Partial"),
                            ("EMPTY", "Empty (Awaiting Refill)"),
                            ("AT_VENDOR", "At Vendor (Refilling)"),
                            ("IN_USE", "In Use"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("RETIRED", "Retired / Condemned"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=15,
                    ),
                ),
                (
                    "fill_percentage",
                    models.PositiveIntegerField(
                        default=100, help_text="0-100, current fill level"
                    ),
                ),
                (
                    "current_location",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 'OT-1', 'ICU-A', 'Storage Bay 2'",
                        max_length=120,
                    ),
                ),
                ("manufacture_date", models.DateField(blank=True, null=True)),
                (
                    "manufacturer",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "last_hydro_test",
                    models.DateField(
                        blank=True, help_text="Last hydrostatic test date", null=True
                    ),
                ),
                ("next_hydro_test_due", models.DateField(blank=True, null=True)),
                ("last_refilled_at", models.DateTimeField(blank=True, null=True)),
                ("refill_count", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cylinders",
                        to="department.department",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cylinders",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["cylinder_type__gas_type", "serial_number"],
            },
        ),
        migrations.CreateModel(
            name="CylinderInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_type",
                    models.CharField(
                        choices=[
                            ("VISUAL", "Visual Inspection"),
                            ("PRESSURE", "Pressure Test"),
                            ("HYDRO", "Hydrostatic Test"),
                            ("VALVE", "Valve Inspection"),
                            ("PURITY", "Gas Purity Test"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("PASSED", "Passed"),
                            ("FAILED", "Failed"),
                            ("CONDITIONAL", "Conditional Pass (recheck recommended)"),
                        ],
                        default="PASSED",
                        max_length=15,
                    ),
                ),
                (
                    "inspected_by",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "inspection_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("next_due_date", models.DateField(blank=True, null=True)),
                ("findings", models.TextField(blank=True, default="")),
                (
                    "certificate_ref",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "cylinder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="gas_cylinder.cylinder",
                    ),
                ),
            ],
            options={
                "ordering": ["-inspection_date"],
            },
        ),
        migrations.CreateModel(
            name="CylinderType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Internal code, e.g. O2-D, N2O-E",
                        max_length=20,
                    ),
                ),
                (
                    "gas_type",
                    models.CharField(
                        choices=[
                            ("O2", "Medical Oxygen"),
                            ("N2O", "Nitrous Oxide"),
                            ("MED_AIR", "Medical Air"),
                            ("CO2", "Carbon Dioxide"),
                            ("HELIUM", "Helium"),
                            ("ENTONOX", "Entonox (N2O+O2)"),
                            ("VACUUM", "Vacuum / Suction"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("A", "Size A (Small portable, ~150L)"),
                            ("D", "Size D (Portable, ~415L)"),
                            ("E", "Size E (Tank, ~680L)"),
                            ("M", "Size M (3000L)"),
                            ("H", "Size H (Jumbo, ~7000L)"),
                            ("J", "Size J (Huge, ~12000L)"),
                            ("LIQ", "Liquid bulk tank"),
                        ],
                        max_length=5,
                    ),
                ),
                ("capacity_litres", models.PositiveIntegerField(default=0)),
                (
                    "typical_pressure_kpa",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Working pressure in kPa, e.g. 13700 (137 bar)",
                    ),
                ),
                (
                    "refill_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "deposit_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, default="", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cylinder_types",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["gas_type", "size"],
                "unique_together": {("hospital", "code")},
            },
        ),
        migrations.AddField(
            model_name="cylinder",
            name="cylinder_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cylinders",
                to="gas_cylinder.cylindertype",
            ),
        ),
        migrations.CreateModel(
            name="CylinderUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("ISSUED", "Issued to Ward / Department"),
                            ("RETURNED", "Returned to Storage"),
                            ("CONNECTED", "Connected to Patient / Manifold"),
                            ("DISCONNECTED", "Disconnected"),
                            ("REFILL_OUT", "Sent for Refill"),
                            ("REFILL_IN", "Received from Refill"),
                            ("INSPECTION", "Routine Inspection"),
                            ("DISCARDED", "Discarded"),
                        ],
                        max_length=15,
                    ),
                ),
                ("location", models.CharField(blank=True, default="", max_length=120)),
                (
                    "fill_at_event",
                    models.PositiveIntegerField(
                        default=0, help_text="Fill % at time of event"
                    ),
                ),
                (
                    "received_by",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Free-text staff name receiving the cylinder",
                        max_length=120,
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=300)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "cylinder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_log",
                        to="gas_cylinder.cylinder",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cylinder_usage",
                        to="department.department",
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="RefillRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated, e.g. RF-20260508-0001",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("vendor_name", models.CharField(max_length=120)),
                (
                    "vendor_contact",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expected_return_at", models.DateTimeField(blank=True, null=True)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("cylinders_sent", models.PositiveIntegerField(default=0)),
                ("cylinders_received", models.PositiveIntegerField(default=0)),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                (
                    "invoice_reference",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cylinder_refills",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddIndex(
            model_name="cylinder",
            index=models.Index(
                fields=["status", "cylinder_type"], name="gas_cylinde_status_0a2e71_idx"
            ),
        ),
    ]
