# Generated by Django 5.2.14 on 2026-05-27 02:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafeguardingConcern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('reference_number', models.CharField(help_text="Human-readable reference (e.g. 'SG-2026-0001'). Unique per hospital.", max_length=30)),
                ('subject_description', models.CharField(blank=True, default='', help_text="Description of the subject if no patient FK (e.g. 'Female child ~5yo, accompanying patient MRN1234').", max_length=300)),
                ('category', models.CharField(choices=[('CHILD_ABUSE', 'Child abuse'), ('ELDER_ABUSE', 'Elder abuse'), ('DOMESTIC_VIOLENCE', 'Domestic violence'), ('NEGLECT', 'Neglect'), ('SEXUAL_ASSAULT', 'Sexual assault'), ('SELF_HARM', 'Self-harm / suicide risk'), ('MENTAL_HEALTH', 'Mental health crisis'), ('FINANCIAL_EXPLOITATION', 'Financial exploitation'), ('TRAFFICKING', 'Human trafficking'), ('OTHER', 'Other')], db_index=True, max_length=24)),
                ('risk_level', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('CRITICAL', 'Critical — immediate action')], db_index=True, default='MODERATE', max_length=10)),
                ('observations', models.TextField(help_text='What was observed / disclosed / suspected. Be specific but stick to facts, not opinions.')),
                ('location_of_concern', models.CharField(blank=True, default='', help_text='Where the concern was observed (department, ward, home).', max_length=200)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open / investigating'), ('ESCALATED', 'Escalated to external agency'), ('CLOSED', 'Closed — internal action only'), ('CANCELLED', 'Cancelled / withdrawn')], db_index=True, default='DRAFT', max_length=10)),
                ('raised_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, db_index=True, help_text='When the concern reached a terminal status. Once set, the concern body is sealed.', null=True)),
                ('closure_summary', models.TextField(blank=True, default='', help_text='Brief summary of why the concern was closed/escalated. Set on transition to terminal status.')),
                ('additional_viewers', models.ManyToManyField(blank=True, help_text='Other staff explicitly granted view access (e.g. ward manager, senior physician). Without inclusion here, the concern is invisible to them.', related_name='safeguarding_viewable', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hospital')),
                ('investigator', models.ForeignKey(blank=True, help_text='Designated safeguarding lead assigned to investigate.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='safeguarding_investigating', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, help_text="The patient at risk. Null only if subject is not a registered patient (visitor's child, accompanying spouse).", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='safeguarding_concerns', to='core.patient')),
                ('reporter', models.ForeignKey(help_text='Staff member who raised the concern.', on_delete=django.db.models.deletion.PROTECT, related_name='safeguarding_reported', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-raised_at'],
            },
        ),
        migrations.CreateModel(
            name='ConcernReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('agency_type', models.CharField(choices=[('POLICE', 'Police'), ('CPS', 'Child Protective Services'), ('SOCIAL_SERVICES', 'Social Services / Welfare Dept'), ('MENTAL_HEALTH', 'Mental Health Authority'), ('ELDER_SERVICES', 'Elder Services'), ('WOMENS_HELPLINE', "Women's Helpline / Cell"), ('CHILDLINE', 'Childline (1098)'), ('NCPCR', 'National Commission for Protection of Child Rights'), ('OTHER', 'Other agency')], db_index=True, max_length=18)),
                ('agency_name', models.CharField(help_text="Specific agency name (e.g. 'Meerut Police, Civil Lines PS').", max_length=200)),
                ('contact_person', models.CharField(blank=True, default='', help_text='Officer / case worker contacted, if known.', max_length=200)),
                ('contact_details', models.CharField(blank=True, default='', help_text='Phone / email / address.', max_length=300)),
                ('referred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('reference_id_from_agency', models.CharField(blank=True, default='', help_text='FIR number, case number, etc. — issued by the agency.', max_length=80)),
                ('summary_shared', models.TextField(help_text='What information was shared with the agency. Critical for chain of custody / disclosure tracking.')),
                ('outcome', models.CharField(choices=[('PENDING', 'Pending response'), ('ACCEPTED', 'Accepted for action'), ('DECLINED', 'Declined / outside remit'), ('INVESTIGATING', 'Under investigation by agency'), ('RESOLVED', 'Resolved by agency'), ('UNKNOWN', 'Outcome unknown / no follow-up')], db_index=True, default='PENDING', help_text='Outcome reported back from the agency. Updatable via /update-outcome/ action, not via PUT.', max_length=14)),
                ('outcome_notes', models.TextField(blank=True, default='')),
                ('outcome_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hospital')),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='safeguarding_referrals_made', to=settings.AUTH_USER_MODEL)),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='referrals', to='protection.safeguardingconcern')),
            ],
            options={
                'ordering': ['-referred_at'],
            },
        ),
        migrations.CreateModel(
            name='ConcernNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('note_type', models.CharField(choices=[('OBSERVATION', 'Observation'), ('INTERVIEW', 'Interview'), ('ACTION_TAKEN', 'Action taken'), ('DECISION', 'Decision / determination'), ('FOLLOWUP', 'Follow-up required'), ('OTHER', 'Other')], db_index=True, default='OBSERVATION', max_length=14)),
                ('body', models.TextField()),
                ('addendum_to', models.ForeignKey(blank=True, help_text='If this note is an addendum/correction to an earlier note, link to it here. The original stays in the record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addenda', to='protection.concernnote')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='safeguarding_notes', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hospital')),
                ('concern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='protection.safeguardingconcern')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='safeguardingconcern',
            index=models.Index(fields=['status', '-raised_at'], name='protection__status_60d882_idx'),
        ),
        migrations.AddIndex(
            model_name='safeguardingconcern',
            index=models.Index(fields=['risk_level', 'status'], name='protection__risk_le_339e5c_idx'),
        ),
        migrations.AddIndex(
            model_name='safeguardingconcern',
            index=models.Index(fields=['category', '-raised_at'], name='protection__categor_1f9ef5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='safeguardingconcern',
            unique_together={('hospital', 'reference_number')},
        ),
        migrations.AddIndex(
            model_name='concernreferral',
            index=models.Index(fields=['concern', '-referred_at'], name='protection__concern_c62cbd_idx'),
        ),
        migrations.AddIndex(
            model_name='concernreferral',
            index=models.Index(fields=['agency_type', 'outcome'], name='protection__agency__ab3755_idx'),
        ),
        migrations.AddIndex(
            model_name='concernnote',
            index=models.Index(fields=['concern', '-created_at'], name='protection__concern_285c60_idx'),
        ),
    ]
