# Generated by Django 5.1.4 on 2026-05-12 06:22

import apps.hr.models
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("department", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("title", models.CharField(max_length=120)),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("EXEC", "Executive"),
                            ("MGR", "Manager"),
                            ("SR", "Senior"),
                            ("MID", "Mid-level"),
                            ("JR", "Junior"),
                            ("TRAINEE", "Trainee"),
                        ],
                        default="MID",
                        max_length=10,
                    ),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="designations",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["grade", "title"],
                "unique_together": {("hospital", "code")},
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_code",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated, e.g. EMP-2026-0001",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=60)),
                (
                    "middle_name",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                ("last_name", models.CharField(max_length=60)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        default="M",
                        max_length=1,
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("UNK", "Unknown"),
                        ],
                        default="UNK",
                        max_length=5,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("phone", models.CharField(db_index=True, max_length=20)),
                (
                    "alternate_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.TextField(blank=True, default="")),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "aadhaar_number",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="12-digit Aadhaar",
                        max_length=12,
                    ),
                ),
                ("pan_number", models.CharField(blank=True, default="", max_length=10)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("PERM", "Permanent"),
                            ("CONTRACT", "Contract"),
                            ("CONSULTANT", "Visiting Consultant"),
                            ("INTERN", "Intern"),
                            ("LOCUM", "Locum"),
                        ],
                        default="PERM",
                        max_length=15,
                    ),
                ),
                ("date_of_joining", models.DateField()),
                ("date_of_leaving", models.DateField(blank=True, null=True)),
                ("probation_end_date", models.DateField(blank=True, null=True)),
                ("confirmation_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("ON_LEAVE", "On Long Leave"),
                            ("SUSPENDED", "Suspended"),
                            ("RESIGNED", "Resigned"),
                            ("TERMINATED", "Terminated"),
                            ("RETIRED", "Retired"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=12,
                    ),
                ),
                ("bank_name", models.CharField(blank=True, default="", max_length=100)),
                (
                    "bank_account_number",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("bank_ifsc", models.CharField(blank=True, default="", max_length=15)),
                ("pf_number", models.CharField(blank=True, default="", max_length=30)),
                ("uan_number", models.CharField(blank=True, default="", max_length=15)),
                ("esi_number", models.CharField(blank=True, default="", max_length=20)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employees",
                        to="department.department",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="hr.designation",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employees",
                        to="core.hospital",
                    ),
                ),
                (
                    "reports_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="direct_reports",
                        to="hr.employee",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["employee_code"],
            },
        ),
        migrations.CreateModel(
            name="EmploymentContract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_number", models.CharField(db_index=True, max_length=30)),
                ("start_date", models.DateField()),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="Null for permanent contracts", null=True
                    ),
                ),
                (
                    "monthly_salary",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("notice_period_days", models.PositiveIntegerField(default=30)),
                ("is_active", models.BooleanField(default=True)),
                ("contract_terms", models.TextField(blank=True, default="")),
                ("signed_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="hr.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="LeaveType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True, help_text="e.g. CL, SL, EL, ML", max_length=20
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "days_per_year",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("12.0"), max_digits=5
                    ),
                ),
                ("is_paid", models.BooleanField(default=True)),
                ("is_carry_forward", models.BooleanField(default=False)),
                (
                    "max_carry_forward",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("0"), max_digits=5
                    ),
                ),
                ("requires_attachment", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_types",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="LeaveRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=30, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("num_days", models.DecimalField(decimal_places=1, max_digits=5)),
                ("reason", models.TextField()),
                (
                    "contact_during_leave",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SUBMITTED",
                        max_length=12,
                    ),
                ),
                ("applied_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("decision_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision_notes",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("attachment_url", models.URLField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leaves_approved",
                        to="hr.employee",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leave_requests",
                        to="hr.employee",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_requests",
                        to="core.hospital",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="requests",
                        to="hr.leavetype",
                    ),
                ),
            ],
            options={
                "ordering": ["-applied_at"],
            },
        ),
        migrations.CreateModel(
            name="LeaveBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(default=apps.hr.models._current_year),
                ),
                ("allocated", models.DecimalField(decimal_places=1, max_digits=5)),
                (
                    "used",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "pending",
                    models.DecimalField(
                        decimal_places=1, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leave_balances",
                        to="hr.employee",
                    ),
                ),
                (
                    "leave_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balances",
                        to="hr.leavetype",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["status", "department"], name="hr_employee_status_7e01e4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leavetype",
            unique_together={("hospital", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="leavebalance",
            unique_together={("employee", "leave_type", "year")},
        ),
    ]
