# Generated by Django 5.1.4 on 2026-05-12 06:22

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AttendanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "punch_time",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "punch_type",
                    models.CharField(
                        choices=[("IN", "Punch In"), ("OUT", "Punch Out")], max_length=3
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("MANUAL", "Manual Entry"),
                            ("BIOMETRIC", "Biometric"),
                            ("WEB", "Web App"),
                            ("MOBILE", "Mobile App"),
                            ("CARD", "Access Card"),
                        ],
                        default="MANUAL",
                        max_length=10,
                    ),
                ),
                ("location", models.CharField(blank=True, default="", max_length=200)),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
            ],
            options={
                "ordering": ["-punch_time"],
            },
        ),
        migrations.CreateModel(
            name="DailyAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PRESENT", "Present"),
                            ("ABSENT", "Absent"),
                            ("HALF_DAY", "Half Day"),
                            ("LATE", "Late"),
                            ("ON_LEAVE", "On Leave"),
                            ("HOLIDAY", "Holiday"),
                            ("OFF_DAY", "Off Day"),
                            ("WEEKEND", "Weekend"),
                        ],
                        default="ABSENT",
                        max_length=10,
                    ),
                ),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "hours_worked",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                ("late_minutes", models.PositiveIntegerField(default=0)),
                ("early_leave_minutes", models.PositiveIntegerField(default=0)),
                ("is_remarked", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, default="", max_length=300)),
            ],
            options={
                "ordering": ["-work_date"],
            },
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("name", models.CharField(max_length=100)),
                ("is_optional", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Overtime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=4)),
                ("reason", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="REQUESTED",
                        max_length=10,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-work_date"],
            },
        ),
        migrations.CreateModel(
            name="Shift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(max_length=80)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("break_minutes", models.PositiveIntegerField(default=30)),
                (
                    "work_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("8"), max_digits=4
                    ),
                ),
                ("is_night_shift", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["start_time"],
            },
        ),
        migrations.CreateModel(
            name="ShiftRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("work_date", models.DateField(db_index=True)),
                ("is_off_day", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
            ],
            options={
                "ordering": ["work_date"],
            },
        ),
    ]
