# Generated by Django 5.1.4 on 2026-05-12 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        ("core", "0001_initial"),
        ("hr", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancelog",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_logs",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="attendancelog",
            name="recorded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dailyattendance",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daily_attendance",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="holiday",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="holidays",
                to="core.hospital",
            ),
        ),
        migrations.AddField(
            model_name="overtime",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="overtime_approvals",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="overtime",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="overtimes",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="shift",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shifts",
                to="core.hospital",
            ),
        ),
        migrations.AddField(
            model_name="shiftroster",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rosters",
                to="hr.employee",
            ),
        ),
        migrations.AddField(
            model_name="shiftroster",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rosters",
                to="attendance.shift",
            ),
        ),
        migrations.AddIndex(
            model_name="attendancelog",
            index=models.Index(
                fields=["employee", "punch_time"], name="attendance__employe_1f7b08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dailyattendance",
            index=models.Index(
                fields=["status", "work_date"], name="attendance__status_82f08e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailyattendance",
            unique_together={("employee", "work_date")},
        ),
        migrations.AlterUniqueTogether(
            name="holiday",
            unique_together={("hospital", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="shift",
            unique_together={("hospital", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="shiftroster",
            unique_together={("employee", "work_date")},
        ),
    ]
