# Generated by Django 5.1.4 on 2026-05-08 07:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0002_invoice_amount_refunded_alter_invoice_code_and_more"),
        ("core", "0001_initial"),
        ("opd", "0001_initial"),
        ("specialist", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LabOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Auto e.g. LAB-20260507-0001",
                        max_length=20,
                    ),
                ),
                (
                    "order_date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("ROUTINE", "Routine"),
                            ("URGENT", "Urgent"),
                            ("STAT", "STAT (immediate)"),
                        ],
                        default="ROUTINE",
                        max_length=10,
                    ),
                ),
                (
                    "clinical_notes",
                    models.TextField(
                        blank=True,
                        help_text="Provisional diagnosis / why these tests were ordered",
                    ),
                ),
                ("requires_fasting", models.BooleanField(default=False)),
                ("fasting_hours", models.PositiveSmallIntegerField(default=0)),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "igst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("ORDERED", "Ordered (awaiting sample)"),
                            ("COLLECTED", "Sample collected"),
                            ("IN_PROGRESS", "Tests in progress"),
                            ("REPORTED", "Reported"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("sample_collected_at", models.DateTimeField(blank=True, null=True)),
                ("reported_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_orders",
                        to="opd.consultation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_order",
                        to="billing.invoice",
                    ),
                ),
                (
                    "ordered_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ordered_lab_orders",
                        to="specialist.doctor",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lab_orders",
                        to="core.patient",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pathologist / radiologist who signed the report",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_lab_orders",
                        to="specialist.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["-order_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LabSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "sample_type",
                    models.CharField(
                        choices=[
                            ("BLOOD", "Blood"),
                            ("URINE", "Urine"),
                            ("STOOL", "Stool"),
                            ("SPUTUM", "Sputum"),
                            ("SWAB", "Swab"),
                            ("CSF", "CSF"),
                            ("TISSUE", "Tissue/biopsy"),
                            ("IMAGE", "Imaging (no sample)"),
                            ("OTHER", "Other"),
                        ],
                        default="BLOOD",
                        max_length=10,
                    ),
                ),
                (
                    "container",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'EDTA purple-top', 'plain red-top', 'fluoride grey-top'",
                        max_length=80,
                    ),
                ),
                (
                    "barcode",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Auto-generated unique label for the tube",
                        max_length=40,
                    ),
                ),
                (
                    "volume",
                    models.CharField(
                        blank=True, help_text="e.g. '3 ml', '10 ml'", max_length=30
                    ),
                ),
                (
                    "collected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "is_received",
                    models.BooleanField(
                        default=True, help_text="Lab has physically received the sample"
                    ),
                ),
                (
                    "is_rejected",
                    models.BooleanField(
                        default=False,
                        help_text="Sample is unusable (haemolysed/clotted/insufficient)",
                    ),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=200)),
                ("notes", models.CharField(blank=True, max_length=300)),
                (
                    "collected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collected_samples",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="samples",
                        to="lab.laborder",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "-collected_at"],
            },
        ),
        migrations.CreateModel(
            name="TestCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique short code, e.g. CBC, LFT, KFT, LIPID, FBS",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name, e.g. 'Complete Blood Count'",
                        max_length=200,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("HEMATOLOGY", "Haematology"),
                            ("BIOCHEMISTRY", "Biochemistry"),
                            ("MICROBIOLOGY", "Microbiology"),
                            ("SEROLOGY", "Serology / Immunology"),
                            ("URINALYSIS", "Urinalysis"),
                            ("RADIOLOGY", "Radiology / Imaging"),
                            ("PATHOLOGY", "Pathology / Histology"),
                            ("OTHER", "Other"),
                        ],
                        default="HEMATOLOGY",
                        max_length=15,
                    ),
                ),
                (
                    "sample_type",
                    models.CharField(
                        choices=[
                            ("BLOOD", "Blood"),
                            ("URINE", "Urine"),
                            ("STOOL", "Stool"),
                            ("SPUTUM", "Sputum"),
                            ("SWAB", "Swab"),
                            ("CSF", "CSF"),
                            ("TISSUE", "Tissue/biopsy"),
                            ("IMAGE", "Imaging (no sample)"),
                            ("OTHER", "Other"),
                        ],
                        default="BLOOD",
                        max_length=10,
                    ),
                ),
                (
                    "sample_volume",
                    models.CharField(
                        blank=True,
                        help_text="e.g. '3 ml in EDTA tube', '10 ml mid-stream'",
                        max_length=30,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Patient price (pre-GST)",
                        max_digits=10,
                    ),
                ),
                (
                    "hsn_code",
                    models.CharField(blank=True, default="9993", max_length=8),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Most diagnostic services are GST-exempt in India (0%)",
                        max_digits=5,
                    ),
                ),
                (
                    "typical_tat_hours",
                    models.PositiveSmallIntegerField(
                        default=24,
                        help_text="Typical turnaround time in hours, used for ETA display",
                    ),
                ),
                ("requires_fasting", models.BooleanField(default=False)),
                (
                    "instructions",
                    models.TextField(
                        blank=True,
                        help_text="Pre-test instructions to print on the order slip",
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test catalog item",
                "verbose_name_plural": "Test catalog",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="LabOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "test_code",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized from test.code at order time",
                        max_length=20,
                    ),
                ),
                (
                    "test_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized from test.name at order time",
                        max_length=200,
                    ),
                ),
                (
                    "sample_type",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized from test.sample_type",
                        max_length=10,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Charged price at order time (snapshot)",
                        max_digits=10,
                    ),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "gst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=300)),
                ("order_index", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="lab.laborder",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lab.testcatalog",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "order_index"],
            },
        ),
        migrations.CreateModel(
            name="TestParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "code",
                    models.CharField(
                        help_text="Short code unique within the test, e.g. 'HB', 'RBC', 'SGOT'",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Full name, e.g. 'Haemoglobin'", max_length=120
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'g/dL', 'mg/dL', 'cells/cumm'",
                        max_length=20,
                    ),
                ),
                (
                    "ref_low",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "ref_high",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "ref_text",
                    models.CharField(
                        blank=True,
                        help_text="Free-text range, used when value is qualitative (e.g. 'Negative', 'Non-reactive')",
                        max_length=120,
                    ),
                ),
                (
                    "critical_low",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "critical_high",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                (
                    "is_qualitative",
                    models.BooleanField(
                        default=False,
                        help_text="If True the result is text (Positive/Negative) not numeric",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameters",
                        to="lab.testcatalog",
                    ),
                ),
            ],
            options={
                "ordering": ["test", "sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "parameter_name",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized from parameter.name",
                        max_length=120,
                    ),
                ),
                (
                    "parameter_unit",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized from parameter.unit",
                        max_length=20,
                    ),
                ),
                (
                    "parameter_ref",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized human-readable range, e.g. '12.0 - 17.0'",
                        max_length=80,
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        help_text="Raw entered value as string (preserves precision/format)",
                        max_length=80,
                    ),
                ),
                (
                    "flag",
                    models.CharField(
                        choices=[
                            ("NORMAL", "Normal"),
                            ("LOW", "Low"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        db_index=True,
                        default="NORMAL",
                        max_length=10,
                    ),
                ),
                (
                    "interpretation",
                    models.CharField(
                        blank=True,
                        help_text="Optional clinical comment from the pathologist",
                        max_length=300,
                    ),
                ),
                ("entered_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_results_entered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="results",
                        to="lab.laborderitem",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lab_results_verified",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="lab.testparameter",
                    ),
                ),
            ],
            options={
                "ordering": ["order_item", "sort_order"],
            },
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(
                fields=["patient", "-order_date"], name="lab_laborde_patient_a1baa0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(
                fields=["status", "-order_date"], name="lab_laborde_status_156876_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="laborder",
            index=models.Index(
                fields=["priority", "-order_date"],
                name="lab_laborde_priorit_72b587_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="laborder",
            unique_together={("hospital", "code")},
        ),
        migrations.AddIndex(
            model_name="labsample",
            index=models.Index(
                fields=["barcode"], name="lab_labsamp_barcode_6227d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="labsample",
            index=models.Index(
                fields=["order", "sample_type"], name="lab_labsamp_order_i_8a72a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="testcatalog",
            index=models.Index(
                fields=["category", "is_active"], name="lab_testcat_categor_28f777_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="testcatalog",
            unique_together={("hospital", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="testparameter",
            unique_together={("test", "code")},
        ),
        migrations.AddIndex(
            model_name="labresult",
            index=models.Index(
                fields=["flag", "-entered_at"], name="lab_labresu_flag_d72170_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="labresult",
            unique_together={("order_item", "parameter")},
        ),
    ]
