# Generated by Django 5.1.4 on 2026-05-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lab", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="labsample",
            name="volume",
            field=models.CharField(
                blank=True, help_text="e.g. '3 ml', '10 ml'", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="testcatalog",
            name="sample_volume",
            field=models.CharField(
                blank=True,
                help_text="e.g. '3 ml in EDTA tube', '10 ml mid-stream'",
                max_length=100,
            ),
        ),
    ]
