# Generated by Django 5.1.4 on 2026-05-11 11:35

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HKStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_code",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("CLEANER", "Cleaner"),
                            ("SUPERVISOR", "Supervisor"),
                            ("DEEP_CLEAN", "Deep Cleaning Specialist"),
                            ("PEST", "Pest Control"),
                        ],
                        default="CLEANER",
                        max_length=12,
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("MORNING", "Morning (06-14)"),
                            ("AFTERNOON", "Afternoon (14-22)"),
                            ("NIGHT", "Night (22-06)"),
                            ("FLEXI", "Flexi"),
                        ],
                        default="FLEXI",
                        max_length=10,
                    ),
                ),
                ("is_on_duty", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hk_staff",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "verbose_name": "Housekeeping Staff",
                "verbose_name_plural": "Housekeeping Staff",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="HKZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(max_length=120)),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("WARD", "Ward / Patient Room"),
                            ("OT", "Operation Theatre"),
                            ("ICU", "ICU"),
                            ("OPD", "OPD / Consultation"),
                            ("LAB", "Laboratory"),
                            ("LOBBY", "Lobby / Public Area"),
                            ("TOILET", "Toilet / Restroom"),
                            ("KITCHEN", "Kitchen"),
                            ("CORRIDOR", "Corridor"),
                            ("CAFETERIA", "Cafeteria"),
                            ("OFFICE", "Office"),
                            ("STORE", "Store"),
                            ("OTHER", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("HIGH", "High (OT, ICU, isolation)"),
                            ("MEDIUM", "Medium (wards, labs)"),
                            ("LOW", "Low (offices, corridors)"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("floor", models.CharField(blank=True, default="", max_length=20)),
                ("area_sqft", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hk_zones",
                        to="department.department",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hk_zones",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["floor", "code"],
                "unique_together": {("hospital", "code")},
            },
        ),
        migrations.CreateModel(
            name="HKTaskTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(max_length=120)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("MOP", "Floor Mopping"),
                            ("SWEEP", "Sweeping"),
                            ("DUST", "Dusting"),
                            ("SANITIZE", "Sanitization"),
                            ("WASTE", "Waste Collection"),
                            ("LINEN", "Linen Change"),
                            ("DEEP", "Deep Cleaning"),
                            ("FUMIGATE", "Fumigation"),
                            ("OTHER", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("HOURLY", "Hourly"),
                            ("EVERY_2H", "Every 2 hours"),
                            ("EVERY_4H", "Every 4 hours"),
                            ("DAILY", "Once Daily"),
                            ("TWICE", "Twice Daily"),
                            ("THRICE", "Thrice Daily"),
                            ("WEEKLY", "Weekly"),
                            ("MONTHLY", "Monthly"),
                        ],
                        default="DAILY",
                        max_length=10,
                    ),
                ),
                ("duration_minutes", models.PositiveIntegerField(default=15)),
                ("instructions", models.TextField(blank=True, default="")),
                (
                    "chemicals_required",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hk_task_templates",
                        to="core.hospital",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_templates",
                        to="housekeeping.hkzone",
                    ),
                ),
            ],
            options={
                "ordering": ["zone", "task_type"],
                "unique_together": {("hospital", "code")},
            },
        ),
        migrations.CreateModel(
            name="DeepCleaningSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("DEEP_CLEAN", "Deep Cleaning"),
                            ("FUMIGATION", "Fumigation"),
                            ("PEST", "Pest Control"),
                            ("DISINFECT", "Terminal Disinfection"),
                        ],
                        max_length=12,
                    ),
                ),
                ("scheduled_date", models.DateField()),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="SCHEDULED",
                        max_length=12,
                    ),
                ),
                (
                    "vendor_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="External vendor if outsourced",
                        max_length=200,
                    ),
                ),
                ("chemicals_used", models.TextField(blank=True, default="")),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("next_due_date", models.DateField(blank=True, null=True)),
                (
                    "certificate_reference",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deep_cleanings",
                        to="core.hospital",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deep_cleanings",
                        to="housekeeping.hkzone",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="HKTaskAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("scheduled_date", models.DateField(db_index=True)),
                ("scheduled_time", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("MISSED", "Missed"),
                            ("REJECTED", "Rejected (Quality Check)"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "quality_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="1-5 stars from supervisor check",
                        null=True,
                    ),
                ),
                (
                    "quality_notes",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to="housekeeping.hkstaff",
                    ),
                ),
                (
                    "inspected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="inspected_tasks",
                        to="housekeeping.hkstaff",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="housekeeping.hktasktemplate",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_assignments",
                        to="housekeeping.hkzone",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_date", "scheduled_time"],
                "indexes": [
                    models.Index(
                        fields=["status", "scheduled_date"],
                        name="housekeepin_status_4a6ea2_idx",
                    ),
                    models.Index(
                        fields=["assigned_to", "scheduled_date"],
                        name="housekeepin_assigne_c4f6a4_idx",
                    ),
                ],
            },
        ),
    ]
