# Generated by Django 5.2.14 on 2026-05-26 17:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Account code (e.g. '1000', '4100-OPD'). Unique per hospital.", max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], db_index=True, max_length=10)),
                ('is_postable', models.BooleanField(default=True, help_text='False = group/header account; True = leaf that takes journal lines.')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hospital')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent group account, if this is a sub-account.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='accounting.account')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('entry_number', models.CharField(help_text="Human-readable voucher number (e.g. 'JV-2026-0001').", max_length=30)),
                ('entry_date', models.DateField(db_index=True, help_text='Date of the transaction (not the system time).')),
                ('narration', models.TextField(help_text='What this entry is for (visible in reports).')),
                ('reference', models.CharField(blank=True, default='', help_text='External reference: invoice no, cheque no, etc.', max_length=80)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('POSTED', 'Posted')], db_index=True, default='DRAFT', max_length=8)),
                ('posted_at', models.DateTimeField(blank=True, help_text='When the entry was POSTED. Null = still DRAFT.', null=True)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Set to True when the fiscal period is closed. Posted entries inside a locked period cannot be reversed.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hospital')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_entries_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Journal entries',
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('narration', models.CharField(blank=True, default='', help_text='Optional line-level narration (overrides entry narration in reports).', max_length=200)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='accounting.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journalentry')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['entry', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type', 'code'], name='accounting__account_000d21_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['parent', 'code'], name='accounting__parent__ae1c4f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together={('hospital', 'code')},
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['status', '-entry_date'], name='accounting__status_edfa8d_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['-entry_date', '-id'], name='accounting__entry_d_2b4b45_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journalentry',
            unique_together={('hospital', 'entry_number')},
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account', 'entry'], name='accounting__account_e026d4_idx'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['entry'], name='accounting__entry_i_0f9370_idx'),
        ),
    ]
