# Generated by Django 5.1.4 on 2026-05-25 12:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_invoice_amount_refunded_alter_invoice_code_and_more'),
        ('core', '0001_initial'),
        ('ipd', '0001_initial'),
        ('specialist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationTheatre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Short code, e.g. OT-1, OT-CARDIAC-A', max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('theatre_type', models.CharField(choices=[('GENERAL', 'General Surgery'), ('CARDIAC', 'Cardiac'), ('NEURO', 'Neurosurgery'), ('OBGYN', 'OB/GYN'), ('ORTHO', 'Orthopaedics'), ('MINOR', 'Minor OT / Day-Care'), ('EMERGENCY', 'Emergency')], default='GENERAL', max_length=15)),
                ('floor', models.CharField(blank=True, default='', max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied'), ('CLEANING', 'Cleaning / Turnover'), ('MAINTENANCE', 'Under Maintenance')], default='AVAILABLE', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theatres', to='core.hospital')),
            ],
            options={
                'verbose_name': 'Operation Theatre',
                'ordering': ['theatre_type', 'code'],
                'unique_together': {('hospital', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SurgeryBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Auto-generated, e.g. OT-20260508-0001', max_length=30, unique=True)),
                ('urgency', models.CharField(choices=[('ELECTIVE', 'Elective'), ('URGENT', 'Urgent (within 24h)'), ('EMERGENCY', 'Emergency')], default='ELECTIVE', max_length=12)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CHECKED_IN', 'Patient Checked-In'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('POSTPONED', 'Postponed')], default='SCHEDULED', max_length=15)),
                ('scheduled_start', models.DateTimeField()),
                ('scheduled_end', models.DateTimeField()),
                ('actual_start', models.DateTimeField(blank=True, null=True)),
                ('actual_end', models.DateTimeField(blank=True, null=True)),
                ('pre_op_diagnosis', models.CharField(blank=True, default='', max_length=300)),
                ('pre_op_assessment', models.TextField(blank=True, default='')),
                ('consent_obtained', models.BooleanField(default=False)),
                ('consent_witness', models.CharField(blank=True, default='', max_length=120)),
                ('locked_procedure_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('locked_gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=300)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries', to='ipd.admission')),
                ('anaesthetist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries_as_anaesthetist', to='specialist.doctor')),
                ('booked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_surgeries', to=settings.AUTH_USER_MODEL)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_surgeries', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_bookings', to='core.hospital')),
                ('invoice', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_booking', to='billing.invoice')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surgery_bookings', to='core.patient')),
                ('primary_surgeon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='surgeries_as_primary', to='specialist.doctor')),
                ('theatre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='ot.operationtheatre')),
            ],
            options={
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='OTRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_op_findings', models.TextField(blank=True, default='')),
                ('surgical_steps', models.TextField(blank=True, default='', help_text='Step-by-step narrative of the procedure')),
                ('intra_op_findings', models.TextField(blank=True, default='')),
                ('complications', models.TextField(blank=True, default='')),
                ('blood_loss_ml', models.PositiveIntegerField(default=0)),
                ('blood_transfused_units', models.PositiveIntegerField(default=0)),
                ('instruments_used', models.TextField(blank=True, default='')),
                ('implants_used', models.TextField(blank=True, default='', help_text='Implants, prostheses, mesh, etc. with batch numbers')),
                ('specimens_sent', models.TextField(blank=True, default='', help_text='Histopathology / culture specimens dispatched')),
                ('anaesthesia_type', models.CharField(blank=True, default='', max_length=30)),
                ('anaesthesia_notes', models.TextField(blank=True, default='')),
                ('post_op_orders', models.TextField(blank=True, default='')),
                ('condition_on_shifting', models.CharField(blank=True, default='', help_text='Patient condition while shifting to recovery / ward', max_length=120)),
                ('prepared_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finalized_at', models.DateTimeField(blank=True, null=True)),
                ('prepared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prepared_ot_registers', to='specialist.doctor')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ot_register', to='ot.surgerybooking')),
            ],
            options={
                'verbose_name': 'OT Register',
                'verbose_name_plural': 'OT Registers',
            },
        ),
        migrations.CreateModel(
            name='OTConsumable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_ot_consumables', to=settings.AUTH_USER_MODEL)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumables', to='ot.surgerybooking')),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.CreateModel(
            name='SurgeryTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(blank=True, default='', help_text='Free-text name when team member is not in Doctor table', max_length=120)),
                ('role', models.CharField(choices=[('SURGEON', 'Primary Surgeon'), ('ASSISTANT', 'Assistant Surgeon'), ('ANAESTHETIST', 'Anaesthetist'), ('NURSE_SCRUB', 'Scrub Nurse'), ('NURSE_CIRCULATING', 'Circulating Nurse'), ('TECHNICIAN', 'OT Technician'), ('PERFUSIONIST', 'Perfusionist'), ('OBSERVER', 'Observer')], max_length=20)),
                ('notes', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='ot.surgerybooking')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgery_team_assignments', to='specialist.doctor')),
            ],
            options={
                'ordering': ['role'],
            },
        ),
        migrations.CreateModel(
            name='SurgicalProcedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('GENERAL', 'General Surgery'), ('CARDIAC', 'Cardiac'), ('NEURO', 'Neurosurgery'), ('OBGYN', 'OB/GYN'), ('ORTHO', 'Orthopaedics'), ('ENT', 'ENT'), ('OPHTHAL', 'Ophthalmology'), ('UROLOGY', 'Urology'), ('GASTRO', 'Gastrointestinal'), ('ONCO', 'Oncology'), ('PLASTIC', 'Plastic / Reconstructive'), ('MINOR', 'Minor')], default='GENERAL', max_length=15)),
                ('typical_duration_minutes', models.PositiveIntegerField(default=60, help_text='Estimated theatre booking duration')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('hsn_code', models.CharField(blank=True, default='9993', max_length=8)),
                ('gst_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Most healthcare procedures are GST-exempt; cosmetic/aesthetic = 18%', max_digits=5)),
                ('requires_anaesthesia', models.BooleanField(default=True)),
                ('anaesthesia_type', models.CharField(blank=True, default='', help_text='GA / SA / LA / EPIDURAL / NONE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgical_procedures', to='core.hospital')),
            ],
            options={
                'ordering': ['category', 'name'],
                'unique_together': {('hospital', 'code')},
            },
        ),
        migrations.AddField(
            model_name='surgerybooking',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='ot.surgicalprocedure'),
        ),
        migrations.AddIndex(
            model_name='surgerybooking',
            index=models.Index(fields=['status', 'scheduled_start'], name='ot_surgeryb_status_a38687_idx'),
        ),
        migrations.AddIndex(
            model_name='surgerybooking',
            index=models.Index(fields=['theatre', 'scheduled_start'], name='ot_surgeryb_theatre_ce647b_idx'),
        ),
    ]
