# Generated by Django 5.1.4 on 2026-05-07 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                            ("EMAIL", "Email"),
                            ("IN_APP", "In-App"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        blank=True, help_text="Email only", max_length=200
                    ),
                ),
                (
                    "body",
                    models.TextField(help_text="Use {placeholders} for substitution"),
                ),
                (
                    "msg91_template_id",
                    models.CharField(
                        blank=True,
                        help_text="DLT-approved template ID for MSG91",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "unique_together": {("hospital", "code", "channel")},
            },
        ),
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("SMS", "SMS"),
                            ("WHATSAPP", "WhatsApp"),
                            ("EMAIL", "Email"),
                            ("IN_APP", "In-App"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "to_address",
                    models.CharField(
                        db_index=True,
                        help_text="Phone, email, or user_id",
                        max_length=200,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                            ("DELIVERED", "Delivered"),
                            ("READ", "Read"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True, help_text="msg91 / console / smtp", max_length=20
                    ),
                ),
                ("provider_message_id", models.CharField(blank=True, max_length=100)),
                ("error", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "related_object_type",
                    models.CharField(
                        blank=True,
                        help_text="appointment, bill, otp, etc.",
                        max_length=50,
                    ),
                ),
                ("related_object_id", models.CharField(blank=True, max_length=50)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="notifications.notificationtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "channel"],
                        name="notificatio_status_d69daf_idx",
                    ),
                    models.Index(
                        fields=["related_object_type", "related_object_id"],
                        name="notificatio_related_df6367_idx",
                    ),
                ],
            },
        ),
    ]
