# Generated by Django 5.1.4 on 2026-05-12 06:22

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("department", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SecurityGuard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_code",
                    models.CharField(db_index=True, max_length=20, unique=True),
                ),
                ("full_name", models.CharField(max_length=120)),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("is_supervisor", models.BooleanField(default=False)),
                (
                    "posted_at",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Gate / area assigned",
                        max_length=100,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="security_guards",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "incident_number",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated, e.g. INC-20260508-0001",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("THEFT", "Theft / Burglary"),
                            ("VIOLENCE", "Violence / Assault"),
                            ("VANDALISM", "Vandalism"),
                            ("FIRE", "Fire / Smoke"),
                            ("MEDICAL", "Medical Emergency"),
                            ("UNAUTH", "Unauthorized Entry"),
                            ("LOST_FOUND", "Lost & Found"),
                            ("ACCIDENT", "Accident"),
                            ("OTHER", "Other"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="LOW",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REPORTED", "Reported"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("RESOLVED", "Resolved"),
                            ("ESCALATED", "Escalated to Police"),
                            ("CLOSED", "Closed"),
                        ],
                        default="REPORTED",
                        max_length=12,
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("location", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("persons_involved", models.TextField(blank=True, default="")),
                ("witnesses", models.TextField(blank=True, default="")),
                ("police_involved", models.BooleanField(default=False)),
                ("fir_number", models.CharField(blank=True, default="", max_length=50)),
                (
                    "estimated_loss",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("actions_taken", models.TextField(blank=True, default="")),
                ("resolution", models.TextField(blank=True, default="")),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidents",
                        to="department.department",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidents",
                        to="core.hospital",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_incidents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "handled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="handled_incidents",
                        to="security_module.securityguard",
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.CreateModel(
            name="GatePass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pass_number",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated, e.g. GP-20260508-0001",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "pass_type",
                    models.CharField(
                        choices=[
                            ("RETURNABLE", "Returnable"),
                            ("NON_RETURNABLE", "Non-returnable"),
                        ],
                        default="RETURNABLE",
                        max_length=15,
                    ),
                ),
                (
                    "items_description",
                    models.TextField(
                        help_text="Itemized list of goods/equipment going out"
                    ),
                ),
                ("purpose", models.TextField()),
                (
                    "issued_to_party",
                    models.CharField(
                        help_text="Person/company taking material out", max_length=200
                    ),
                ),
                (
                    "issued_to_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "vehicle_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expected_return_at", models.DateTimeField(blank=True, null=True)),
                ("actual_return_at", models.DateTimeField(blank=True, null=True)),
                (
                    "estimated_value",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ISSUED", "Issued (Out)"),
                            ("RETURNED", "Returned"),
                            ("OVERDUE", "Overdue"),
                            ("CLOSED", "Closed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ISSUED",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_gate_passes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gate_passes",
                        to="core.hospital",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_gate_passes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_gate_passes",
                        to="department.department",
                    ),
                ),
                (
                    "received_at_gate_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="gate_passes_received",
                        to="security_module.securityguard",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="VisitorPass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pass_number",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated, e.g. VST-20260508-0001",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("visitor_name", models.CharField(max_length=120)),
                ("visitor_phone", models.CharField(db_index=True, max_length=20)),
                (
                    "id_proof_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Aadhaar/PAN/Driving License/Voter ID",
                        max_length=30,
                    ),
                ),
                (
                    "id_proof_number",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("photo_url", models.URLField(blank=True, default="")),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("PATIENT", "Patient Visit"),
                            ("ATTENDANT", "Patient Attendant"),
                            ("VENDOR", "Vendor / Supplier"),
                            ("OFFICIAL", "Official"),
                            ("DELIVERY", "Delivery / Courier"),
                            ("OTHER", "Other"),
                        ],
                        default="PATIENT",
                        max_length=12,
                    ),
                ),
                ("purpose", models.CharField(blank=True, default="", max_length=300)),
                (
                    "visiting_person",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="If not visiting a registered patient",
                        max_length=120,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "room_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("entry_time", models.DateTimeField(default=django.utils.timezone.now)),
                ("expected_exit_time", models.DateTimeField(blank=True, null=True)),
                ("actual_exit_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active (Inside)"),
                            ("EXITED", "Exited"),
                            ("EXPIRED", "Expired (Auto)"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department_to_visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="visitor_passes",
                        to="department.department",
                    ),
                ),
                (
                    "exit_logged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exit_logged_passes",
                        to="security_module.securityguard",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitor_passes",
                        to="core.hospital",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_passes",
                        to="security_module.securityguard",
                    ),
                ),
                (
                    "visiting_patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_visitor_passes",
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-entry_time"],
                "indexes": [
                    models.Index(
                        fields=["status", "entry_time"],
                        name="security_mo_status_6b09b6_idx",
                    )
                ],
            },
        ),
    ]
