# Generated by Django 5.2.14 on 2026-05-26 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('department', '0001_initial'),
        ('ipd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('POLICY', 'Policy / SOP update'), ('CLINICAL', 'Clinical alert'), ('OPERATIONAL', 'Operational / logistics'), ('TRAINING', 'Training / education'), ('HR', 'HR announcement'), ('SAFETY', 'Safety / incident'), ('OTHER', 'Other')], db_index=True, default='OPERATIONAL', max_length=12)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=8)),
                ('audience_type', models.CharField(choices=[('HOSPITAL', 'Hospital-wide — all staff'), ('DEPARTMENT', 'Department'), ('WARD', 'Ward')], db_index=True, default='HOSPITAL', max_length=10)),
                ('requires_acknowledgment', models.BooleanField(db_index=True, default=False)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional: bulletin auto-hides from inbox after this time.', null=True)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('audience_department', models.ForeignKey(blank=True, help_text='Required when audience_type=DEPARTMENT.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins', to='department.department')),
                ('audience_ward', models.ForeignKey(blank=True, help_text='Required when audience_type=WARD.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletins', to='ipd.ward')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletins_authored', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulletinAcknowledgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('acknowledged_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('note', models.CharField(blank=True, default='', help_text="Optional comment on the ack (e.g. 'will discuss in team meeting').", max_length=300)),
                ('bulletin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgments', to='internal_comms.bulletin')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hospital')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletin_acks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-acknowledged_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('subject', models.CharField(blank=True, default='', help_text='Optional subject line. Empty for quick replies.', max_length=200)),
                ('body', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='NORMAL', max_length=8)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, help_text='When the recipient marked this as read. Null = unread.', null=True)),
                ('is_archived_by_sender', models.BooleanField(db_index=True, default=False)),
                ('is_archived_by_recipient', models.BooleanField(db_index=True, default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hospital')),
                ('parent_message', models.ForeignKey(blank=True, help_text='Set if this message is a reply to an earlier one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='internal_comms.message')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bulletin',
            index=models.Index(fields=['audience_type', '-created_at'], name='internal_co_audienc_f61acc_idx'),
        ),
        migrations.AddIndex(
            model_name='bulletin',
            index=models.Index(fields=['priority', '-created_at'], name='internal_co_priorit_72f4d4_idx'),
        ),
        migrations.AddIndex(
            model_name='bulletinacknowledgment',
            index=models.Index(fields=['bulletin', '-acknowledged_at'], name='internal_co_bulleti_cd6332_idx'),
        ),
        migrations.AddIndex(
            model_name='bulletinacknowledgment',
            index=models.Index(fields=['user', '-acknowledged_at'], name='internal_co_user_id_752ea8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bulletinacknowledgment',
            unique_together={('bulletin', 'user')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'read_at', '-created_at'], name='internal_co_recipie_66e317_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', '-created_at'], name='internal_co_sender__94e2e9_idx'),
        ),
    ]
