# Generated by Django 5.2.14 on 2026-05-27 02:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="Code identifier (e.g. 'CODE_BLUE'). Unique per hospital.", max_length=30)),
                ('name', models.CharField(help_text="Short display name (e.g. 'Code Blue').", max_length=80)),
                ('description', models.TextField(help_text='What this code means and when to activate.')),
                ('color', models.CharField(blank=True, default='', help_text="Display color hint (e.g. 'blue', 'red', '#0066cc').", max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='False = retired code; existing activations stay valid.')),
                ('requires_evacuation', models.BooleanField(default=False, help_text='If True, UI should prominently show evacuation guidance.')),
                ('default_response_minutes', models.PositiveIntegerField(default=5, help_text='Expected response time SLA for drills (minutes).')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hospital')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Drill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('scheduled_at', models.DateTimeField(db_index=True, help_text='Planned date/time of the drill.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, help_text='When the drill ended. Once set, entry is immutable.', null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=12)),
                ('location', models.CharField(help_text='Where the drill is/was conducted.', max_length=200)),
                ('rating', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('SATISFACTORY', 'Satisfactory'), ('NEEDS_IMPROVEMENT', 'Needs improvement'), ('FAILED', 'Failed — major issues')], default='', help_text="Observer's rating after drill completion.", max_length=20)),
                ('expected_response_seconds', models.PositiveIntegerField(blank=True, help_text='Target response time for this drill type.', null=True)),
                ('actual_response_seconds', models.PositiveIntegerField(blank=True, help_text='Observed response time.', null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Drill objectives, scenario description, lessons learned.')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hospital')),
                ('observers', models.ManyToManyField(blank=True, related_name='drills_observed', to=settings.AUTH_USER_MODEL)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drills_organized', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='drills_participated', to=settings.AUTH_USER_MODEL)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drills', to='crisis.emergencycode')),
            ],
            options={
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('called_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, db_index=True, help_text='When the first responder arrived on scene.', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, help_text='When the code was stood down. Once set, entry is immutable.', null=True)),
                ('location', models.CharField(help_text="Where in the hospital (free text: 'ICU bed C-04', 'Lift lobby 3F', etc.).", max_length=200)),
                ('notes', models.TextField(blank=True, default='', help_text='What happened, what was done, anything notable.')),
                ('outcome', models.CharField(blank=True, choices=[('RESOLVED', 'Resolved successfully'), ('FALSE_ALARM', 'False alarm / no incident'), ('ESCALATED', 'Escalated to external services (police/fire/EMS)'), ('FATALITY', 'Patient fatality'), ('OTHER', 'Other outcome')], default='', help_text='Set on resolve. Empty while activation is live.', max_length=12)),
                ('outcome_notes', models.TextField(blank=True, default='', help_text='Detailed outcome notes (lessons learned, follow-up needed).')),
                ('called_by', models.ForeignKey(help_text='Staff member who activated the code.', on_delete=django.db.models.deletion.PROTECT, related_name='codes_called', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, help_text='Department / area, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_activations', to='department.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hospital')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_activations', to='core.patient')),
                ('responders', models.ManyToManyField(blank=True, help_text='Staff who responded. Add via /add-responder/ action.', related_name='codes_responded_to', to=settings.AUTH_USER_MODEL)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activations', to='crisis.emergencycode')),
            ],
            options={
                'ordering': ['-called_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emergencycode',
            index=models.Index(fields=['is_active', 'code'], name='crisis_emer_is_acti_e08198_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emergencycode',
            unique_together={('hospital', 'code')},
        ),
        migrations.AddIndex(
            model_name='drill',
            index=models.Index(fields=['status', '-scheduled_at'], name='crisis_dril_status_a4cf38_idx'),
        ),
        migrations.AddIndex(
            model_name='drill',
            index=models.Index(fields=['-scheduled_at', 'code'], name='crisis_dril_schedul_bd76da_idx'),
        ),
        migrations.AddIndex(
            model_name='codeactivation',
            index=models.Index(fields=['-called_at', 'code'], name='crisis_code_called__05d908_idx'),
        ),
        migrations.AddIndex(
            model_name='codeactivation',
            index=models.Index(fields=['resolved_at'], name='crisis_code_resolve_361637_idx'),
        ),
    ]
