# Generated by Django 5.1.4 on 2026-05-07 05:28

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("legal_name", models.CharField(blank=True, max_length=200)),
                ("address_line1", models.CharField(max_length=200)),
                ("address_line2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("pincode", models.CharField(max_length=10)),
                ("country", models.CharField(default="India", max_length=100)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "gst_number",
                    models.CharField(
                        blank=True, help_text="15-char GSTIN", max_length=15
                    ),
                ),
                ("pan_number", models.CharField(blank=True, max_length=10)),
                (
                    "registration_number",
                    models.CharField(
                        blank=True,
                        help_text="Hospital licence/registration number",
                        max_length=50,
                    ),
                ),
                ("nabh_accredited", models.BooleanField(default=False)),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=50)),
                ("currency", models.CharField(default="INR", max_length=3)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="hospital_logos/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalPatient",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, db_index=True, editable=False),
                ),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "uuid",
                    models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
                ),
                (
                    "mrn",
                    models.CharField(
                        db_index=True,
                        help_text="Medical Record Number, auto-generated",
                        max_length=30,
                    ),
                ),
                (
                    "abha_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ABDM Health ID (14-digit)",
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("dob", models.DateField()),
                (
                    "age_estimated",
                    models.BooleanField(
                        default=False, help_text="True if DOB is approximate"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("UNK", "UNK"),
                        ],
                        default="UNK",
                        max_length=5,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("DIVORCED", "Divorced"),
                            ("WIDOWED", "Widowed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=15)),
                ("alt_phone", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "aadhaar_last4",
                    models.CharField(
                        blank=True,
                        help_text="Last 4 digits only (DPDP compliance)",
                        max_length=4,
                    ),
                ),
                ("pan_number", models.CharField(blank=True, max_length=10)),
                ("address_line1", models.CharField(blank=True, max_length=200)),
                ("address_line2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10)),
                ("country", models.CharField(default="India", max_length=100)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=15),
                ),
                (
                    "emergency_contact_relation",
                    models.CharField(blank=True, max_length=50),
                ),
                ("occupation", models.CharField(blank=True, max_length=100)),
                ("nationality", models.CharField(default="Indian", max_length=50)),
                (
                    "allergies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of dicts: [{"substance":"Penicillin","severity":"high"}]',
                    ),
                ),
                ("chronic_conditions", models.JSONField(blank=True, default=list)),
                ("current_medications", models.JSONField(blank=True, default=list)),
                ("photo", models.TextField(blank=True, max_length=100, null=True)),
                ("is_vip", models.BooleanField(default=False)),
                ("is_deceased", models.BooleanField(default=False)),
                ("deceased_at", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical patient",
                "verbose_name_plural": "historical patients",
                "db_table": "core_patient_history",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("code", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=100)),
                (
                    "dept_type",
                    models.CharField(
                        choices=[
                            ("CLINICAL", "Clinical"),
                            ("DIAGNOSTIC", "Diagnostic"),
                            ("SUPPORT", "Support"),
                            ("ADMIN", "Administrative"),
                        ],
                        default="CLINICAL",
                        max_length=20,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "head_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_departments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="core.department",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("hospital", "code")},
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Login"),
                            ("LOGOUT", "Logout"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("PASSWORD_CHANGE", "Password Change"),
                            ("PERM_CHANGE", "Permission Change"),
                            ("DATA_EXPORT", "Data Export"),
                            ("BREAK_GLASS", "Break-glass Access"),
                            ("REPORT_GEN", "Report Generated"),
                            ("BULK_IMPORT", "Bulk Import"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("target_type", models.CharField(blank=True, max_length=100)),
                ("target_id", models.CharField(blank=True, max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="core_auditl_action_29a2bf_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("code", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=100)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("WARD", "Ward"),
                            ("ROOM", "Room"),
                            ("OT", "Operation Theatre"),
                            ("ICU", "ICU"),
                            ("LAB", "Laboratory"),
                            ("PHARMACY", "Pharmacy"),
                            ("STORE", "Store"),
                            ("OPD", "OPD Cabin"),
                            ("RECEPTION", "Reception"),
                            ("OFFICE", "Office"),
                            ("KITCHEN", "Kitchen"),
                            ("LAUNDRY", "Laundry"),
                            ("OTHER", "Other"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("floor", models.CharField(blank=True, max_length=20)),
                ("block", models.CharField(blank=True, max_length=20)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=0, help_text="Beds, seats, or 0 if not applicable"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.department",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["location_type", "name"],
                "unique_together": {("hospital", "code")},
            },
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "mrn",
                    models.CharField(
                        db_index=True,
                        help_text="Medical Record Number, auto-generated",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "abha_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="ABDM Health ID (14-digit)",
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(blank=True, max_length=100)),
                ("dob", models.DateField()),
                (
                    "age_estimated",
                    models.BooleanField(
                        default=False, help_text="True if DOB is approximate"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("UNK", "UNK"),
                        ],
                        default="UNK",
                        max_length=5,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SINGLE", "Single"),
                            ("MARRIED", "Married"),
                            ("DIVORCED", "Divorced"),
                            ("WIDOWED", "Widowed"),
                        ],
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(db_index=True, max_length=15)),
                ("alt_phone", models.CharField(blank=True, max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "aadhaar_last4",
                    models.CharField(
                        blank=True,
                        help_text="Last 4 digits only (DPDP compliance)",
                        max_length=4,
                    ),
                ),
                ("pan_number", models.CharField(blank=True, max_length=10)),
                ("address_line1", models.CharField(blank=True, max_length=200)),
                ("address_line2", models.CharField(blank=True, max_length=200)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                ("pincode", models.CharField(blank=True, max_length=10)),
                ("country", models.CharField(default="India", max_length=100)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=15),
                ),
                (
                    "emergency_contact_relation",
                    models.CharField(blank=True, max_length=50),
                ),
                ("occupation", models.CharField(blank=True, max_length=100)),
                ("nationality", models.CharField(default="Indian", max_length=50)),
                (
                    "allergies",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of dicts: [{"substance":"Penicillin","severity":"high"}]',
                    ),
                ),
                ("chronic_conditions", models.JSONField(blank=True, default=list)),
                ("current_medications", models.JSONField(blank=True, default=list)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="patients/photos/"
                    ),
                ),
                ("is_vip", models.BooleanField(default=False)),
                ("is_deceased", models.BooleanField(default=False)),
                ("deceased_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["hospital", "phone"],
                        name="core_patien_hospita_e824a1_idx",
                    ),
                    models.Index(
                        fields=["hospital", "first_name", "last_name"],
                        name="core_patien_hospita_6719c1_idx",
                    ),
                ],
            },
        ),
    ]
