# Generated by Django 5.1.4 on 2026-05-11 06:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("ipd", "0001_initial"),
        ("specialist", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DietType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True, default="")),
                ("calories_per_day", models.PositiveIntegerField(default=0)),
                ("protein_g", models.PositiveIntegerField(default=0)),
                ("carbs_g", models.PositiveIntegerField(default=0)),
                ("fat_g", models.PositiveIntegerField(default=0)),
                ("sodium_mg", models.PositiveIntegerField(default=0)),
                ("is_diabetic_safe", models.BooleanField(default=False)),
                ("is_renal_safe", models.BooleanField(default=False)),
                ("is_cardiac_safe", models.BooleanField(default=False)),
                ("is_low_sodium", models.BooleanField(default=False)),
                ("is_gluten_free", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diet_types",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "unique_together": {("hospital", "code")},
            },
        ),
        migrations.CreateModel(
            name="DietPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_vegetarian", models.BooleanField(default=True)),
                ("is_jain", models.BooleanField(default=False)),
                ("is_diabetic", models.BooleanField(default=False)),
                (
                    "allergies",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Comma-separated, e.g. 'peanuts, shellfish'",
                        max_length=300,
                    ),
                ),
                (
                    "food_preferences",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Patient/family preferences — likes, dislikes",
                    ),
                ),
                (
                    "fluid_restriction_ml",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Daily fluid limit (renal patients)",
                        null=True,
                    ),
                ),
                (
                    "npo_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Patient is NPO until this datetime",
                        null=True,
                    ),
                ),
                (
                    "npo_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("started_at", models.DateField(default=django.utils.timezone.now)),
                ("ended_at", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused (NPO)"),
                            ("ENDED", "Ended"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diet_plans",
                        to="ipd.admission",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diet_plans",
                        to="core.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="diet_plans",
                        to="core.patient",
                    ),
                ),
                (
                    "prescribed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescribed_diet_plans",
                        to="specialist.doctor",
                    ),
                ),
                (
                    "diet_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="plans",
                        to="dietary.diettype",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="MealItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(max_length=120)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("BREAKFAST", "Breakfast (07:30)"),
                            ("MORNING_SNACK", "Mid-morning Snack (10:30)"),
                            ("LUNCH", "Lunch (12:30)"),
                            ("EVENING_SNACK", "Evening Snack (16:30)"),
                            ("DINNER", "Dinner (19:30)"),
                            ("BEDTIME", "Bedtime Snack (21:30)"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("calories", models.PositiveIntegerField(default=0)),
                (
                    "protein_g",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "carbs_g",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "fat_g",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                ("is_vegetarian", models.BooleanField(default=True)),
                ("is_jain", models.BooleanField(default=False)),
                ("contains_gluten", models.BooleanField(default=True)),
                ("contains_dairy", models.BooleanField(default=True)),
                ("contains_nuts", models.BooleanField(default=False)),
                (
                    "cost_per_serving",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meal_items",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["meal_type", "code"],
                "unique_together": {("hospital", "code")},
            },
        ),
        migrations.CreateModel(
            name="KitchenOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_date", models.DateField(db_index=True)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("BREAKFAST", "Breakfast (07:30)"),
                            ("MORNING_SNACK", "Mid-morning Snack (10:30)"),
                            ("LUNCH", "Lunch (12:30)"),
                            ("EVENING_SNACK", "Evening Snack (16:30)"),
                            ("DINNER", "Dinner (19:30)"),
                            ("BEDTIME", "Bedtime Snack (21:30)"),
                        ],
                        max_length=15,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=0)),
                ("notes", models.CharField(blank=True, default="", max_length=300)),
                (
                    "is_finalized",
                    models.BooleanField(
                        default=False,
                        help_text="Once finalized, kitchen counts are locked",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kitchen_orders",
                        to="core.hospital",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="kitchen_orders",
                        to="dietary.mealitem",
                    ),
                ),
            ],
            options={
                "ordering": ["order_date", "meal_type"],
                "unique_together": {("hospital", "order_date", "meal_type", "item")},
            },
        ),
        migrations.CreateModel(
            name="PatientMeal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meal_date", models.DateField(db_index=True)),
                (
                    "meal_type",
                    models.CharField(
                        choices=[
                            ("BREAKFAST", "Breakfast (07:30)"),
                            ("MORNING_SNACK", "Mid-morning Snack (10:30)"),
                            ("LUNCH", "Lunch (12:30)"),
                            ("EVENING_SNACK", "Evening Snack (16:30)"),
                            ("DINNER", "Dinner (19:30)"),
                            ("BEDTIME", "Bedtime Snack (21:30)"),
                        ],
                        db_index=True,
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("IN_KITCHEN", "Being Prepared"),
                            ("READY", "Ready for Delivery"),
                            ("DELIVERED", "Delivered to Patient"),
                            ("CONSUMED", "Consumed"),
                            ("REFUSED", "Refused / Not Consumed"),
                            ("CANCELLED", "Cancelled (NPO / discharge)"),
                        ],
                        default="PLANNED",
                        max_length=12,
                    ),
                ),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "delivered_by",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "consumed_percentage",
                    models.PositiveIntegerField(
                        default=0, help_text="0-100, recorded when nurse logs intake"
                    ),
                ),
                (
                    "refusal_reason",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "diet_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="dietary.dietplan",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="patient_meals",
                        to="dietary.mealitem",
                    ),
                ),
            ],
            options={
                "ordering": ["meal_date", "meal_type"],
                "indexes": [
                    models.Index(
                        fields=["meal_date", "status"],
                        name="dietary_pat_meal_da_07cb3e_idx",
                    )
                ],
                "unique_together": {("diet_plan", "meal_date", "meal_type")},
            },
        ),
    ]
