# Generated by Django 5.1.4 on 2026-05-11 06:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("department", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LaundryBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated, e.g. LB-20260508-0001",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "batch_type",
                    models.CharField(
                        choices=[
                            ("OUTSOURCED", "Outsourced Laundry"),
                            ("IN_HOUSE", "In-house Laundry"),
                        ],
                        default="OUTSOURCED",
                        max_length=15,
                    ),
                ),
                (
                    "source_ward_label",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                (
                    "vendor_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="External laundry vendor (when OUTSOURCED)",
                        max_length=120,
                    ),
                ),
                (
                    "vendor_contact",
                    models.CharField(blank=True, default="", max_length=80),
                ),
                ("pickup_at", models.DateTimeField(blank=True, null=True)),
                ("expected_return_at", models.DateTimeField(blank=True, null=True)),
                ("returned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created (Pickup pending)"),
                            ("PICKED_UP", "Picked Up"),
                            ("WASHING", "At Laundry / Washing"),
                            ("READY", "Ready for Return"),
                            ("RETURNED", "Returned / Received"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="CREATED",
                        max_length=12,
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="laundry_batches",
                        to="core.hospital",
                    ),
                ),
                (
                    "source_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="laundry_batches_source",
                        to="department.department",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LinenItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BEDSHEET", "Bedsheet"),
                            ("PILLOW", "Pillow Cover"),
                            ("BLANKET", "Blanket"),
                            ("TOWEL", "Towel"),
                            ("GOWN", "Patient Gown"),
                            ("SCRUB", "Surgical Scrubs"),
                            ("OT_DRAPE", "OT Drape / Sheet"),
                            ("CURTAIN", "Curtain / Privacy Screen"),
                            ("UNIFORM", "Staff Uniform"),
                            ("OTHER", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("color", models.CharField(blank=True, default="", max_length=30)),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 'S/M/L', '90x190 cm'",
                        max_length=30,
                    ),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=8
                    ),
                ),
                (
                    "laundry_cost_per_wash",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Per-cycle outsourced/in-house laundry cost",
                        max_digits=6,
                    ),
                ),
                ("expected_lifetime_washes", models.PositiveIntegerField(default=100)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, default="", max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linen_items",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["category", "code"],
            },
        ),
        migrations.CreateModel(
            name="LaundryBatchItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_sent", models.PositiveIntegerField(default=0)),
                ("quantity_received", models.PositiveIntegerField(default=0)),
                ("quantity_lost", models.PositiveIntegerField(default=0)),
                ("quantity_damaged", models.PositiveIntegerField(default=0)),
                (
                    "cost_per_unit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                (
                    "line_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("notes", models.CharField(blank=True, default="", max_length=200)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="laundry.laundrybatch",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batch_entries",
                        to="laundry.linenitem",
                    ),
                ),
            ],
            options={
                "ordering": ["item__category"],
            },
        ),
        migrations.CreateModel(
            name="LinenLoss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "loss_type",
                    models.CharField(
                        choices=[
                            ("DAMAGED", "Damaged"),
                            ("LOST", "Lost / Stolen"),
                            ("END_OF_LIFE", "End of Life (worn out)"),
                            ("CONTAMINATED", "Contaminated"),
                        ],
                        max_length=15,
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "cost_impact",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("reason", models.CharField(blank=True, default="", max_length=300)),
                (
                    "reported_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="losses",
                        to="laundry.laundrybatch",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="linen_losses",
                        to="department.department",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linen_losses",
                        to="core.hospital",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="losses",
                        to="laundry.linenitem",
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-reported_at"],
            },
        ),
        migrations.CreateModel(
            name="LinenStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ward_label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Free-text ward/floor when no Department FK",
                        max_length=80,
                    ),
                ),
                (
                    "total_units",
                    models.PositiveIntegerField(
                        default=0, help_text="Total units allocated to this location"
                    ),
                ),
                ("in_use", models.PositiveIntegerField(default=0)),
                ("in_laundry", models.PositiveIntegerField(default=0)),
                ("clean_in_stock", models.PositiveIntegerField(default=0)),
                (
                    "minimum_threshold",
                    models.PositiveIntegerField(
                        default=10, help_text="Trigger reorder alert below this"
                    ),
                ),
                ("last_audit_date", models.DateField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, default="", max_length=300)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linen_stock",
                        to="department.department",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linen_stock",
                        to="core.hospital",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_entries",
                        to="laundry.linenitem",
                    ),
                ),
            ],
            options={
                "ordering": ["item__category", "department"],
            },
        ),
        migrations.AddIndex(
            model_name="laundrybatch",
            index=models.Index(fields=["status"], name="laundry_lau_status_28568d_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="linenitem",
            unique_together={("hospital", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="laundrybatchitem",
            unique_together={("batch", "item")},
        ),
        migrations.AlterUniqueTogether(
            name="linenstock",
            unique_together={("item", "department", "ward_label")},
        ),
    ]
