# Generated by Django 5.1.4 on 2026-05-11 06:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0002_invoice_amount_refunded_alter_invoice_code_and_more"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ambulance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Internal code, e.g. AMB-01, AMB-ALS-A",
                        max_length=20,
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        help_text="Vehicle RC number, e.g. UP-14-AB-1234",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "ambulance_type",
                    models.CharField(
                        choices=[
                            ("BLS", "Basic Life Support (BLS)"),
                            ("ALS", "Advanced Life Support (ALS)"),
                            ("CARDIAC", "Cardiac Care Ambulance"),
                            ("MORTUARY", "Mortuary / Hearse"),
                            ("PT", "Patient Transport"),
                            ("NEONATAL", "Neonatal"),
                        ],
                        default="BLS",
                        max_length=15,
                    ),
                ),
                (
                    "make_model",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. Force Traveller, Tata Winger",
                        max_length=100,
                    ),
                ),
                ("year", models.PositiveIntegerField(default=2020)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("DISPATCHED", "Dispatched / On Call"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("OUT_OF_SERVICE", "Out of Service"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                (
                    "equipment_list",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Comma-separated list, e.g. 'Defibrillator, Oxygen, ECG monitor'",
                    ),
                ),
                (
                    "base_location",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "last_lat",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "last_lng",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("last_location_update", models.DateTimeField(blank=True, null=True)),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("500"),
                        help_text="Flag-down / call-out fee",
                        max_digits=10,
                    ),
                ),
                (
                    "per_km_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("20"),
                        help_text="₹ per kilometre",
                        max_digits=10,
                    ),
                ),
                ("insurance_expiry", models.DateField(blank=True, null=True)),
                ("fitness_expiry", models.DateField(blank=True, null=True)),
                ("puc_expiry", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ambulances",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "unique_together": {("hospital", "code")},
            },
        ),
        migrations.CreateModel(
            name="AmbulanceDriver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_code", models.CharField(max_length=30, unique=True)),
                ("full_name", models.CharField(max_length=120)),
                ("phone", models.CharField(db_index=True, max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("DRIVER", "Driver"),
                            ("PARAMEDIC", "Paramedic"),
                            ("EMT", "EMT"),
                            ("DRIVER_PARAMEDIC", "Driver-cum-Paramedic"),
                        ],
                        default="DRIVER",
                        max_length=20,
                    ),
                ),
                (
                    "license_number",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("license_expiry", models.DateField(blank=True, null=True)),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("MORNING", "Morning (06-14)"),
                            ("AFTERNOON", "Afternoon (14-22)"),
                            ("NIGHT", "Night (22-06)"),
                            ("FLEXI", "Flexi"),
                        ],
                        default="FLEXI",
                        max_length=10,
                    ),
                ),
                ("is_on_duty", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ambulance_drivers",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="Dispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated, e.g. AMB-20260508-0001",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "call_type",
                    models.CharField(
                        choices=[
                            ("EMERGENCY", "Emergency Pickup"),
                            ("INTER_HOSPITAL", "Inter-hospital Transfer"),
                            ("DISCHARGE", "Discharge Drop-off"),
                            ("MORTUARY", "Mortuary Transport"),
                            ("OTHER", "Other"),
                        ],
                        default="EMERGENCY",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("CRITICAL", "Critical (red)"),
                            ("URGENT", "Urgent (orange)"),
                            ("ROUTINE", "Routine (green)"),
                        ],
                        default="URGENT",
                        max_length=10,
                    ),
                ),
                (
                    "patient_name_temp",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="If patient not yet registered",
                        max_length=120,
                    ),
                ),
                (
                    "patient_phone_temp",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "caller_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "caller_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "caller_relation",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Family / bystander / police / etc.",
                        max_length=40,
                    ),
                ),
                ("pickup_address", models.TextField()),
                (
                    "pickup_lat",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "pickup_lng",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "pickup_landmark",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "drop_address",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Defaults to hospital address; can be another facility",
                    ),
                ),
                (
                    "chief_complaint",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("age_estimate", models.PositiveIntegerField(blank=True, null=True)),
                ("is_conscious", models.BooleanField(blank=True, null=True)),
                ("is_breathing", models.BooleanField(blank=True, null=True)),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                ("en_route_at", models.DateTimeField(blank=True, null=True)),
                ("on_scene_at", models.DateTimeField(blank=True, null=True)),
                ("patient_picked_at", models.DateTimeField(blank=True, null=True)),
                ("at_hospital_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("ASSIGNED", "Ambulance Assigned"),
                            ("EN_ROUTE", "En-route to Pickup"),
                            ("ON_SCENE", "On Scene"),
                            ("PATIENT_PICKED", "Patient Picked Up"),
                            ("AT_HOSPITAL", "Arrived at Hospital"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="REQUESTED",
                        max_length=15,
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "cancellation_reason",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ambulance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispatches",
                        to="ambulance.ambulance",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="driven_dispatches",
                        to="ambulance.ambulancedriver",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ambulance_dispatches",
                        to="core.hospital",
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ambulance_dispatch",
                        to="billing.invoice",
                    ),
                ),
                (
                    "paramedic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paramedic_dispatches",
                        to="ambulance.ambulancedriver",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ambulance_dispatches",
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="DispatchLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("STATUS_CHANGE", "Status Change"),
                            ("GPS_UPDATE", "GPS Update"),
                            ("NOTE", "Note"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(blank=True, default="", max_length=15),
                ),
                ("to_status", models.CharField(blank=True, default="", max_length=15)),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=300)),
                (
                    "timestamp",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "dispatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="ambulance.dispatch",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddIndex(
            model_name="dispatch",
            index=models.Index(
                fields=["status", "priority"], name="ambulance_d_status_583a24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dispatch",
            index=models.Index(
                fields=["ambulance", "status"], name="ambulance_d_ambulan_03b8fe_idx"
            ),
        ),
    ]
