# Generated by Django 5.1.4 on 2026-05-07 11:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("reception", "0002_initial"),
        ("specialist", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Consultation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Auto e.g., CONS-20260507-0001",
                        max_length=20,
                    ),
                ),
                (
                    "consultation_date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "chief_complaint",
                    models.TextField(
                        blank=True, help_text="Patient's main complaint, in their words"
                    ),
                ),
                (
                    "history_of_present_illness",
                    models.TextField(
                        blank=True,
                        help_text="HPI - timeline, severity, modifying factors",
                    ),
                ),
                (
                    "past_medical_history",
                    models.TextField(
                        blank=True,
                        help_text="Previous illnesses, surgeries, hospitalizations",
                    ),
                ),
                (
                    "examination_findings",
                    models.TextField(
                        blank=True, help_text="Doctor's physical exam findings"
                    ),
                ),
                (
                    "investigations_advised",
                    models.TextField(
                        blank=True, help_text="Lab tests, imaging recommended"
                    ),
                ),
                (
                    "general_advice",
                    models.TextField(
                        blank=True, help_text="Diet, lifestyle, return precautions"
                    ),
                ),
                ("next_visit_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultations",
                        to="reception.appointment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultations",
                        to="specialist.doctor",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consultations",
                        to="core.patient",
                    ),
                ),
                (
                    "queue_token",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consultation",
                        to="reception.queuetoken",
                    ),
                ),
            ],
            options={
                "ordering": ["-consultation_date", "-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ConsultationDiagnosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "icd10_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="WHO ICD-10 code, e.g., I10 (essential hypertension)",
                        max_length=10,
                    ),
                ),
                (
                    "diagnosis_text",
                    models.CharField(
                        help_text="Free-text diagnosis name", max_length=300
                    ),
                ),
                (
                    "diagnosis_type",
                    models.CharField(
                        choices=[
                            ("PROVISIONAL", "Provisional"),
                            ("CONFIRMED", "Confirmed"),
                            ("DIFFERENTIAL", "Differential"),
                            ("FINAL", "Final"),
                        ],
                        default="PROVISIONAL",
                        max_length=15,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("order_index", models.PositiveSmallIntegerField(default=0)),
                (
                    "consultation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diagnoses",
                        to="opd.consultation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Consultation diagnoses",
                "ordering": ["consultation", "-is_primary", "order_index"],
            },
        ),
        migrations.CreateModel(
            name="DrugMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True, help_text="Internal SKU code", max_length=30
                    ),
                ),
                ("generic_name", models.CharField(db_index=True, max_length=200)),
                (
                    "brand_name",
                    models.CharField(blank=True, db_index=True, max_length=200),
                ),
                (
                    "dosage_form",
                    models.CharField(
                        choices=[
                            ("TABLET", "Tablet"),
                            ("CAPSULE", "Capsule"),
                            ("SYRUP", "Syrup"),
                            ("INJECTION", "Injection"),
                            ("OINTMENT", "Ointment"),
                            ("CREAM", "Cream"),
                            ("DROPS", "Drops"),
                            ("INHALER", "Inhaler"),
                            ("LOTION", "Lotion"),
                            ("POWDER", "Powder"),
                            ("SUPPOSITORY", "Suppository"),
                            ("SPRAY", "Spray"),
                            ("OTHER", "Other"),
                        ],
                        default="TABLET",
                        max_length=15,
                    ),
                ),
                (
                    "strength",
                    models.CharField(help_text="e.g. 500mg, 5mg/5ml", max_length=50),
                ),
                ("manufacturer", models.CharField(blank=True, max_length=200)),
                (
                    "hsn_code",
                    models.CharField(
                        blank=True, help_text="HSN for GST billing", max_length=8
                    ),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("12.00"),
                        help_text="GST % on this drug",
                        max_digits=5,
                    ),
                ),
                (
                    "is_schedule_h",
                    models.BooleanField(
                        default=False, help_text="Schedule H/H1 - controlled substance"
                    ),
                ),
                (
                    "common_dose",
                    models.CharField(
                        blank=True,
                        help_text="Default suggestion, e.g., '1 tab BD after meals'",
                        max_length=100,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["generic_name"],
            },
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Auto e.g., RX-20260507-0001",
                        max_length=20,
                    ),
                ),
                (
                    "prescription_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Encoded in QR for public patient view",
                        unique=True,
                    ),
                ),
                (
                    "prescribed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "general_instructions",
                    models.TextField(
                        blank=True, help_text="Diet, follow-up, when to return"
                    ),
                ),
                (
                    "next_followup_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "is_signed",
                    models.BooleanField(
                        default=False, help_text="Doctor has signed via PIN (Phase 1c)"
                    ),
                ),
                ("signed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prescriptions",
                        to="opd.consultation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to="specialist.doctor",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prescriptions",
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-prescribed_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "drug_name",
                    models.CharField(
                        help_text="Denormalized name (in case drug master entry is renamed/deleted)",
                        max_length=200,
                    ),
                ),
                (
                    "dose",
                    models.CharField(
                        help_text="e.g., 500mg, 1 tab, 10ml", max_length=50
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        help_text="OD/BD/TDS/QID/HS/SOS/STAT or free text",
                        max_length=30,
                    ),
                ),
                ("duration_days", models.PositiveSmallIntegerField(default=5)),
                (
                    "route",
                    models.CharField(
                        choices=[
                            ("ORAL", "Oral"),
                            ("IV", "Intravenous"),
                            ("IM", "Intramuscular"),
                            ("SC", "Subcutaneous"),
                            ("TOPICAL", "Topical"),
                            ("INHALATION", "Inhalation"),
                            ("OPHTHALMIC", "Ophthalmic"),
                            ("NASAL", "Nasal"),
                            ("RECTAL", "Rectal"),
                            ("OTHER", "Other"),
                        ],
                        default="ORAL",
                        max_length=12,
                    ),
                ),
                (
                    "instructions",
                    models.CharField(
                        blank=True,
                        help_text="Before food, with milk, etc.",
                        max_length=200,
                    ),
                ),
                (
                    "is_continued",
                    models.BooleanField(
                        default=False, help_text="Patient is already on this medication"
                    ),
                ),
                ("order_index", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional - allows free-text Rx items",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="opd.drugmaster",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="opd.prescription",
                    ),
                ),
            ],
            options={
                "ordering": ["prescription", "order_index"],
            },
        ),
        migrations.CreateModel(
            name="Vitals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "recorded_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "temperature_c",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="In °C",
                        max_digits=4,
                        null=True,
                    ),
                ),
                ("pulse_bpm", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "bp_systolic",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "bp_diastolic",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "spo2_percent",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="SpO₂ in percent", null=True
                    ),
                ),
                (
                    "respiration_rate",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Breaths per minute", null=True
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "height_cm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "bmi",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Auto-computed from weight/height",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "blood_glucose_mgdl",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Random/fasting blood glucose mg/dL",
                        null=True,
                    ),
                ),
                (
                    "pain_score",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="0–10 numeric rating scale", null=True
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vitals_records",
                        to="core.patient",
                    ),
                ),
                (
                    "queue_token",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vitals",
                        to="reception.queuetoken",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Vitals",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.AddField(
            model_name="consultation",
            name="vitals",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consultations",
                to="opd.vitals",
            ),
        ),
        migrations.AddIndex(
            model_name="drugmaster",
            index=models.Index(
                fields=["generic_name"], name="opd_drugmas_generic_c3cf65_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drugmaster",
            index=models.Index(
                fields=["brand_name"], name="opd_drugmas_brand_n_ec6908_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="drugmaster",
            unique_together={("hospital", "code")},
        ),
        migrations.AddIndex(
            model_name="prescription",
            index=models.Index(
                fields=["patient", "-prescribed_at"],
                name="opd_prescri_patient_a58e83_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="prescription",
            unique_together={("hospital", "code")},
        ),
        migrations.AddIndex(
            model_name="vitals",
            index=models.Index(
                fields=["patient", "-recorded_at"], name="opd_vitals_patient_cb0d49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["patient", "-consultation_date"],
                name="opd_consult_patient_638a99_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="consultation",
            index=models.Index(
                fields=["doctor", "consultation_date"],
                name="opd_consult_doctor__3e5e3f_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="consultation",
            unique_together={("hospital", "code")},
        ),
    ]
