# Generated by Django 5.1.4 on 2026-05-07 11:52

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("opd", "0001_initial"),
        ("reception", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Auto e.g. INV-20260507-0001",
                        max_length=20,
                    ),
                ),
                (
                    "bill_date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                ("patient_state", models.CharField(blank=True, max_length=80)),
                ("hospital_state", models.CharField(blank=True, max_length=80)),
                (
                    "gst_split",
                    models.CharField(
                        choices=[
                            ("INTRA", "Intra-state (CGST + SGST)"),
                            ("INTER", "Inter-state (IGST)"),
                            ("EXEMPT", "Exempt"),
                        ],
                        default="INTRA",
                        max_length=10,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Sum of all line items before discount",
                        max_digits=12,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("discount_reason", models.CharField(blank=True, max_length=200)),
                (
                    "taxable_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="subtotal − discount, on which GST applies",
                        max_digits=12,
                    ),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "igst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="taxable_amount + total GST",
                        max_digits=12,
                    ),
                ),
                (
                    "amount_paid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "amount_due",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PENDING", "Pending payment"),
                            ("PARTIAL", "Partially paid"),
                            ("PAID", "Paid in full"),
                            ("CANCELLED", "Cancelled"),
                            ("REFUNDED", "Refunded"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "printed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time thermal/A4 print was generated",
                        null=True,
                    ),
                ),
                ("cancelled_reason", models.CharField(blank=True, max_length=300)),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="reception.appointment",
                    ),
                ),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoices",
                        to="opd.consultation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-bill_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("CARD", "Card"),
                            ("UPI", "UPI"),
                            ("NETBANKING", "Netbanking"),
                            ("RAZORPAY", "Razorpay (online)"),
                            ("CHEQUE", "Cheque"),
                            ("WALLET", "Wallet"),
                            ("INSURANCE", "Insurance/TPA"),
                            ("OTHER", "Other"),
                        ],
                        default="CASH",
                        max_length=12,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Cheque no, UPI ref, card last4, etc.",
                        max_length=100,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("REFUNDED", "Refunded"),
                        ],
                        default="SUCCESS",
                        max_length=10,
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "razorpay_order_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "razorpay_payment_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("razorpay_signature", models.CharField(blank=True, max_length=256)),
                ("is_signature_verified", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="billing.invoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCatalog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique SKU, e.g. CONS-GEN, XRAY-CHEST, CBC",
                        max_length=30,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CONSULTATION", "Consultation"),
                            ("INVESTIGATION", "Investigation/Lab"),
                            ("PROCEDURE", "Procedure"),
                            ("ROOM", "Room/Bed Rent"),
                            ("MEDICINE", "Medicine"),
                            ("PACKAGE", "Package/Bundle"),
                            ("OTHER", "Other"),
                        ],
                        default="CONSULTATION",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Base price in INR (excluding GST)",
                        max_digits=10,
                    ),
                ),
                (
                    "hsn_code",
                    models.CharField(
                        blank=True,
                        help_text="HSN/SAC code for GST. Common: 9993 (medical), 998311 (consultation)",
                        max_length=8,
                    ),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("18.00"),
                        help_text="GST % - usually 0/5/12/18 for medical",
                        max_digits=5,
                    ),
                ),
                (
                    "is_taxable",
                    models.BooleanField(
                        default=True,
                        help_text="Some services (consultation by individual doctor) are GST-exempt",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service catalog item",
                "verbose_name_plural": "Service catalog",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "service_name",
                    models.CharField(
                        help_text="Denormalized in case master row changes",
                        max_length=200,
                    ),
                ),
                ("hsn_code", models.CharField(blank=True, max_length=8)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1"), max_digits=8
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "discount_pct",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Per-line discount %",
                        max_digits=5,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="(qty × unit_price) − line discount; before GST",
                        max_digits=12,
                    ),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("18.00"), max_digits=5
                    ),
                ),
                (
                    "gst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="subtotal + GST",
                        max_digits=12,
                    ),
                ),
                ("order_index", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="billing.invoice",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional - allows free-text/ad-hoc items",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.servicecatalog",
                    ),
                ),
            ],
            options={
                "ordering": ["invoice", "order_index"],
            },
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["patient", "-bill_date"], name="billing_inv_patient_6e9d5e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["status", "-bill_date"], name="billing_inv_status_62f0b2_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="invoice",
            unique_together={("hospital", "code")},
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["invoice", "status"], name="billing_pay_invoice_a67165_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicecatalog",
            index=models.Index(
                fields=["category", "is_active"], name="billing_ser_categor_785951_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="servicecatalog",
            unique_together={("hospital", "code")},
        ),
    ]
