# Generated by Django 5.1.4 on 2026-05-08 07:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="amount_refunded",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="code",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="printed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="taxable_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="discount_pct",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="billing.servicecatalog",
            ),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="service_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="invoiceitem",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="reference",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="servicecatalog",
            name="code",
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="servicecatalog",
            name="gst_rate",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("18.00"), max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name="servicecatalog",
            name="hsn_code",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name="servicecatalog",
            name="is_taxable",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="servicecatalog",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Auto e.g. RFD-20260507-0001",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash refund"),
                            ("RAZORPAY", "Razorpay refund (online)"),
                            ("BANK_TRANSFER", "Bank transfer"),
                            ("ADJUSTMENT", "Credit adjustment"),
                        ],
                        default="CASH",
                        max_length=15,
                    ),
                ),
                ("reason", models.TextField(help_text="Reason — required for audit")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("APPROVED", "Approved"),
                            ("PROCESSED", "Processed"),
                            ("REJECTED", "Rejected"),
                        ],
                        db_index=True,
                        default="REQUESTED",
                        max_length=12,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "razorpay_refund_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "razorpay_status",
                    models.CharField(
                        blank=True,
                        help_text="Razorpay refund status: pending/processed/failed",
                        max_length=30,
                    ),
                ),
                ("rejection_reason", models.CharField(blank=True, max_length=300)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_refunds",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="refunds",
                        to="billing.invoice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        help_text="Original payment being refunded (preferred for Razorpay)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="refunds",
                        to="billing.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "-created_at"],
                        name="billing_ref_status_68ba22_idx",
                    ),
                    models.Index(
                        fields=["invoice", "-created_at"],
                        name="billing_ref_invoice_617d09_idx",
                    ),
                ],
                "unique_together": {("hospital", "code")},
            },
        ),
    ]
