# Generated by Django 5.1.4 on 2026-05-07 07:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QueueToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "token_no",
                    models.CharField(
                        db_index=True,
                        help_text="e.g. A-001, EM-005, APT-042",
                        max_length=20,
                    ),
                ),
                (
                    "visit_date",
                    models.DateField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("EMERGENCY", "Emergency"),
                            ("URGENT", "Urgent"),
                            ("NORMAL", "Normal"),
                            ("APPOINTMENT", "Appointment"),
                        ],
                        default="NORMAL",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("WAITING", "Waiting"),
                            ("IN_VITALS", "Vitals being taken"),
                            ("IN_CONSULT", "In consultation"),
                            ("DONE", "Done"),
                            ("SKIPPED", "Skipped"),
                        ],
                        db_index=True,
                        default="WAITING",
                        max_length=12,
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("called_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["-visit_date", "-priority", "issued_at"],
            },
        ),
        migrations.CreateModel(
            name="VisitorPass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pass_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Encoded in QR",
                        unique=True,
                    ),
                ),
                (
                    "pass_no",
                    models.CharField(
                        db_index=True,
                        help_text="Human-readable, e.g. VP-20260507-0042",
                        max_length=20,
                    ),
                ),
                ("visitor_name", models.CharField(max_length=100)),
                ("visitor_phone", models.CharField(blank=True, max_length=15)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("ATTENDANT", "Patient Attendant"),
                            ("VISITOR", "General Visitor"),
                            ("VENDOR", "Vendor/Delivery"),
                            ("CONTRACTOR", "Contractor"),
                            ("OFFICIAL", "Official Visit"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        blank=True,
                        help_text="Father, Spouse, Friend, etc.",
                        max_length=30,
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("valid_until", models.DateTimeField()),
                ("entered_at", models.DateTimeField(blank=True, null=True)),
                ("exited_at", models.DateTimeField(blank=True, null=True)),
                ("is_revoked", models.BooleanField(default=False)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="visitor_passes/"
                    ),
                ),
                (
                    "id_proof_type",
                    models.CharField(
                        blank=True,
                        help_text="AADHAAR / VOTER / DL / PASSPORT / OTHER",
                        max_length=20,
                    ),
                ),
                ("id_proof_last4", models.CharField(blank=True, max_length=4)),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated, e.g., APT-20260507-0001",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField(db_index=True)),
                ("scheduled_time", models.TimeField()),
                ("duration_minutes", models.PositiveSmallIntegerField(default=15)),
                (
                    "visit_type",
                    models.CharField(
                        choices=[
                            ("NEW", "New Patient"),
                            ("FOLLOWUP", "Follow-up"),
                            ("EMERGENCY", "Emergency"),
                            ("TELE", "Tele-consultation"),
                        ],
                        default="NEW",
                        max_length=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("WALK_IN", "Walk-in"),
                            ("PHONE", "Phone"),
                            ("ONLINE", "Online"),
                            ("REFERRAL", "Referral"),
                        ],
                        default="WALK_IN",
                        max_length=10,
                    ),
                ),
                ("reason", models.CharField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BOOKED", "Booked"),
                            ("CONFIRMED", "Confirmed"),
                            ("CHECKED_IN", "Checked-in"),
                            ("IN_CONSULT", "In consultation"),
                            ("COMPLETED", "Completed"),
                            ("NO_SHOW", "No-show"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="BOOKED",
                        max_length=12,
                    ),
                ),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("consult_started_at", models.DateTimeField(blank=True, null=True)),
                ("consult_ended_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_reason", models.CharField(blank=True, max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_date", "scheduled_time"],
            },
        ),
    ]
