# Generated by Django 5.1.4 on 2026-05-07 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("reception", "0001_initial"),
        ("specialist", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="specialist.doctor",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.hospital",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.location",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="core.patient",
            ),
        ),
        migrations.AddField(
            model_name="queuetoken",
            name="appointment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="queue_token",
                to="reception.appointment",
            ),
        ),
        migrations.AddField(
            model_name="queuetoken",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="queuetoken",
            name="doctor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="queue_tokens",
                to="specialist.doctor",
            ),
        ),
        migrations.AddField(
            model_name="queuetoken",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.hospital",
            ),
        ),
        migrations.AddField(
            model_name="queuetoken",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.location",
            ),
        ),
        migrations.AddField(
            model_name="queuetoken",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="queue_tokens",
                to="core.patient",
            ),
        ),
        migrations.AddField(
            model_name="visitorpass",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="visitorpass",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="core.hospital",
            ),
        ),
        migrations.AddField(
            model_name="visitorpass",
            name="visiting_patient",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visitor_passes",
                to="core.patient",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["scheduled_date", "doctor"],
                name="reception_a_schedul_2f0245_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["patient", "-scheduled_date"],
                name="reception_a_patient_867043_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={("hospital", "code")},
        ),
        migrations.AddIndex(
            model_name="queuetoken",
            index=models.Index(
                fields=["visit_date", "doctor", "status"],
                name="reception_q_visit_d_df9d8d_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="queuetoken",
            unique_together={("hospital", "visit_date", "token_no")},
        ),
        migrations.AlterUniqueTogether(
            name="visitorpass",
            unique_together={("hospital", "pass_no")},
        ),
    ]
