# Generated by Django 5.1.4 on 2026-05-12 07:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VaccinationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dose_number", models.PositiveIntegerField(default=1)),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("administered_date", models.DateField(blank=True, null=True)),
                ("next_dose_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SCHEDULED", "Scheduled"),
                            ("ADMINISTERED", "Administered"),
                            ("MISSED", "Missed"),
                            ("REFUSED", "Refused"),
                            ("DEFERRED", "Deferred (Medical)"),
                        ],
                        db_index=True,
                        default="SCHEDULED",
                        max_length=12,
                    ),
                ),
                (
                    "batch_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "administrator_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                (
                    "site_of_injection",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 'Right Deltoid', 'Left Thigh'",
                        max_length=50,
                    ),
                ),
                ("adverse_reactions", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "administered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vaccines_administered",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccination_records",
                        to="core.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccinations",
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-administered_date", "scheduled_date"],
            },
        ),
        migrations.CreateModel(
            name="VaccinationCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_number",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated, e.g. VC-20260508-0001",
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                (
                    "certificate_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="PDF URL if generated externally",
                    ),
                ),
                (
                    "verification_code",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="vaccination.vaccinationrecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at"],
            },
        ),
        migrations.CreateModel(
            name="Vaccine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(max_length=120)),
                ("full_name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "vaccine_type",
                    models.CharField(
                        choices=[
                            ("PAEDIATRIC", "Paediatric / Child"),
                            ("ADULT", "Adult"),
                            ("BOTH", "Both"),
                            ("TRAVEL", "Travel"),
                            ("SEASONAL", "Seasonal (Flu)"),
                            ("PANDEMIC", "Pandemic (COVID)"),
                        ],
                        default="PAEDIATRIC",
                        max_length=12,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("doses_required", models.PositiveIntegerField(default=1)),
                ("booster_required", models.BooleanField(default=False)),
                ("booster_interval_months", models.PositiveIntegerField(default=0)),
                (
                    "route_of_administration",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. IM, SC, Oral, Intranasal",
                        max_length=30,
                    ),
                ),
                (
                    "standard_dose_ml",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.5"), max_digits=4
                    ),
                ),
                (
                    "is_under_uip",
                    models.BooleanField(
                        default=False,
                        help_text="Under Universal Immunization Programme (free)",
                    ),
                ),
                (
                    "standard_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=10
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("contraindications", models.TextField(blank=True, default="")),
                ("side_effects", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccines",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "unique_together": {("hospital", "code")},
            },
        ),
        migrations.AddField(
            model_name="vaccinationrecord",
            name="vaccine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="records",
                to="vaccination.vaccine",
            ),
        ),
        migrations.CreateModel(
            name="ImmunizationSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dose_number", models.PositiveIntegerField()),
                (
                    "age_value",
                    models.PositiveIntegerField(default=0, help_text="0 for birth"),
                ),
                (
                    "age_unit",
                    models.CharField(
                        choices=[
                            ("BIRTH", "At Birth"),
                            ("WEEK", "Weeks"),
                            ("MONTH", "Months"),
                            ("YEAR", "Years"),
                        ],
                        default="MONTH",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. 'OPV-0 at birth', 'DPT-1 at 6 weeks'",
                        max_length=200,
                    ),
                ),
                (
                    "vaccine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule",
                        to="vaccination.vaccine",
                    ),
                ),
            ],
            options={
                "ordering": ["age_unit", "age_value"],
            },
        ),
        migrations.AddIndex(
            model_name="vaccinationrecord",
            index=models.Index(
                fields=["patient", "vaccine"], name="vaccination_patient_e4777e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vaccinationrecord",
            index=models.Index(
                fields=["status", "scheduled_date"],
                name="vaccination_status_954d9a_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vaccinationrecord",
            unique_together={("patient", "vaccine", "dose_number")},
        ),
        migrations.AlterUniqueTogether(
            name="immunizationschedule",
            unique_together={("vaccine", "dose_number")},
        ),
    ]
