# Generated by Django 5.2.14 on 2026-05-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specialist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='on_call',
            field=models.BooleanField(db_index=True, default=False, help_text='Available for after-hours / emergency calls. Toggled from the Specialist roster UI; orthogonal to is_consulting which is about routine OPD availability.'),
        ),
    ]
