# Generated by Django 5.1.4 on 2026-05-08 05:47

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0001_initial"),
        ("core", "0001_initial"),
        ("opd", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DrugBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "batch_no",
                    models.CharField(
                        db_index=True,
                        help_text="Manufacturer batch number printed on the strip/box",
                        max_length=50,
                    ),
                ),
                ("mfg_date", models.DateField(blank=True, null=True)),
                ("expiry_date", models.DateField(db_index=True)),
                (
                    "qty_purchased",
                    models.PositiveIntegerField(
                        default=0, help_text="Original received quantity"
                    ),
                ),
                (
                    "qty_in_stock",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Current on-hand. Decremented on dispense / adjustment",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Cost from supplier (per unit, pre-GST)",
                        max_digits=10,
                    ),
                ),
                (
                    "mrp",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Maximum Retail Price (per unit, GST-inclusive). Selling price.",
                        max_digits=10,
                    ),
                ),
                ("supplier_name", models.CharField(blank=True, max_length=200)),
                ("supplier_invoice_no", models.CharField(blank=True, max_length=50)),
                (
                    "received_at",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                ("hsn_code", models.CharField(blank=True, max_length=8)),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("12.00"), max_digits=5
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="opd.drugmaster",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Drug batches",
                "ordering": ["expiry_date", "received_at"],
            },
        ),
        migrations.CreateModel(
            name="PharmacyOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Auto e.g. PHARM-20260507-0001",
                        max_length=20,
                    ),
                ),
                (
                    "order_date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "cgst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "sgst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "igst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("dispensed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "consultation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_orders",
                        to="opd.consultation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_order",
                        to="billing.invoice",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pharmacy_orders",
                        to="core.patient",
                    ),
                ),
                (
                    "prescription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pharmacy_orders",
                        to="opd.prescription",
                    ),
                ),
            ],
            options={
                "ordering": ["-order_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PharmacyOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "drug_name",
                    models.CharField(
                        help_text="Denormalized from drug.display_name", max_length=200
                    ),
                ),
                (
                    "batch_no",
                    models.CharField(
                        blank=True,
                        help_text="Denormalized from batch.batch_no",
                        max_length=50,
                    ),
                ),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Denormalized from batch.expiry_date",
                        null=True,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "unit_mrp",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="MRP per unit at time of dispense (GST-inclusive)",
                        max_digits=10,
                    ),
                ),
                (
                    "discount_pct",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("12.00"), max_digits=5
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Pre-GST line value (qty × unit_mrp / (1 + gst_rate/100))",
                        max_digits=12,
                    ),
                ),
                (
                    "gst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="qty × unit_mrp − discount",
                        max_digits=12,
                    ),
                ),
                ("order_index", models.PositiveSmallIntegerField(default=0)),
                (
                    "batch",
                    models.ForeignKey(
                        help_text="Specific batch FEFO-allocated at dispense time",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="pharmacy.drugbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="opd.drugmaster"
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pharmacy.pharmacyorder",
                    ),
                ),
                (
                    "prescription_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="dispensed_items",
                        to="opd.prescriptionitem",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "order_index"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE_IN", "Purchase received"),
                            ("DISPENSE_OUT", "Dispensed to patient"),
                            ("RETURN_IN", "Patient return"),
                            ("EXPIRED_OUT", "Removed (expired)"),
                            ("DAMAGED_OUT", "Removed (damaged)"),
                            ("ADJUSTMENT_IN", "Manual adjustment +"),
                            ("ADJUSTMENT_OUT", "Manual adjustment −"),
                        ],
                        max_length=14,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "moved_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "reference_type",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'pharmacy_order', 'manual'",
                        max_length=30,
                    ),
                ),
                ("reference_id", models.CharField(blank=True, max_length=40)),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="pharmacy.drugbatch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "drug",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movements",
                        to="opd.drugmaster",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["-moved_at"],
            },
        ),
        migrations.AddIndex(
            model_name="drugbatch",
            index=models.Index(
                fields=["drug", "expiry_date"], name="pharmacy_dr_drug_id_6f57c2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="drugbatch",
            index=models.Index(
                fields=["expiry_date", "qty_in_stock"],
                name="pharmacy_dr_expiry__e924f6_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="drugbatch",
            unique_together={("hospital", "drug", "batch_no")},
        ),
        migrations.AddIndex(
            model_name="pharmacyorder",
            index=models.Index(
                fields=["patient", "-order_date"], name="pharmacy_ph_patient_c9f370_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pharmacyorder",
            index=models.Index(
                fields=["status", "-order_date"], name="pharmacy_ph_status_301e1b_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pharmacyorder",
            unique_together={("hospital", "code")},
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["drug", "-moved_at"], name="pharmacy_st_drug_id_921ee8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["movement_type", "-moved_at"],
                name="pharmacy_st_movemen_596222_idx",
            ),
        ),
    ]
