# Generated by Django 5.1.4 on 2026-05-12 07:00

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0002_invoice_amount_refunded_alter_invoice_code_and_more"),
        ("core", "0001_initial"),
        ("ipd", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Claim",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated, e.g. CL-20260508-0001",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "claim_type",
                    models.CharField(
                        choices=[
                            ("CASHLESS", "Cashless"),
                            ("REIMBURSEMENT", "Reimbursement"),
                        ],
                        default="CASHLESS",
                        max_length=15,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted to TPA"),
                            ("UNDER_REVIEW", "Under Review"),
                            ("APPROVED", "Approved"),
                            ("PARTIAL", "Partially Approved"),
                            ("REJECTED", "Rejected"),
                            ("SETTLED", "Settled (Paid)"),
                            ("CLOSED", "Closed"),
                        ],
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                (
                    "submission_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "tpa_claim_number",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "bill_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "co_pay_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "deductions",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "claim_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        help_text="Bill - Co-pay - Deductions",
                        max_digits=12,
                    ),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "settled_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                ("settled_date", models.DateField(blank=True, null=True)),
                ("rejection_reason", models.TextField(blank=True, default="")),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claims",
                        to="ipd.admission",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="claims",
                        to="core.hospital",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claims",
                        to="billing.invoice",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="claims",
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-submission_date"],
            },
        ),
        migrations.CreateModel(
            name="ClaimDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("DISCHARGE", "Discharge Summary"),
                            ("BILL", "Hospital Bill"),
                            ("BILLS_PHARMA", "Pharmacy Bills"),
                            ("LAB", "Lab Reports"),
                            ("PHOTOS", "Photos / Imaging"),
                            ("PRESCRIPTION", "Prescriptions"),
                            ("ID_PROOF", "ID Proof"),
                            ("POLICY_COPY", "Policy Copy"),
                            ("CLAIM_FORM", "Claim Form"),
                            ("OTHER", "Other"),
                        ],
                        max_length=15,
                    ),
                ),
                ("document_url", models.URLField()),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="insurance.claim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClaimLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=300)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1"), max_digits=10
                    ),
                ),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_disallowed", models.BooleanField(default=False)),
                (
                    "disallowance_reason",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "claim",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="insurance.claim",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InsuranceCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(max_length=200)),
                ("short_name", models.CharField(blank=True, default="", max_length=50)),
                (
                    "contact_person",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "helpline_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("portal_url", models.URLField(blank=True, default="")),
                (
                    "is_empanelled",
                    models.BooleanField(
                        default=True,
                        help_text="Hospital is empanelled with this insurer",
                    ),
                ),
                ("is_cashless", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insurance_companies",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Insurance Companies",
                "ordering": ["name"],
                "unique_together": {("hospital", "code")},
            },
        ),
        migrations.CreateModel(
            name="PolicyCoverage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_number", models.CharField(db_index=True, max_length=50)),
                (
                    "member_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Member/UHID/Ecard ID",
                        max_length=50,
                    ),
                ),
                (
                    "policy_holder_name",
                    models.CharField(
                        help_text="If different from patient", max_length=120
                    ),
                ),
                (
                    "relation_to_holder",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "cover_type",
                    models.CharField(
                        choices=[
                            ("INDIVIDUAL", "Individual"),
                            ("FAMILY", "Family Floater"),
                            ("GROUP", "Group / Corporate"),
                            ("SENIOR", "Senior Citizen"),
                            ("MATERNITY", "Maternity Add-on"),
                        ],
                        default="INDIVIDUAL",
                        max_length=12,
                    ),
                ),
                (
                    "sum_insured",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "co_pay_percentage",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                ("policy_start_date", models.DateField()),
                ("policy_end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policy_coverages",
                        to="core.hospital",
                    ),
                ),
                (
                    "insurance_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="policies",
                        to="insurance.insurancecompany",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="policies",
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-policy_start_date"],
            },
        ),
        migrations.AddField(
            model_name="claim",
            name="policy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="claims",
                to="insurance.policycoverage",
            ),
        ),
        migrations.CreateModel(
            name="PreAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated, e.g. PA-20260508-0001",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "urgency",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned Admission"),
                            ("EMERG", "Emergency"),
                        ],
                        default="PLANNED",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted to TPA"),
                            ("APPROVED", "Approved"),
                            ("PARTIAL", "Partially Approved"),
                            ("REJECTED", "Rejected"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=12,
                    ),
                ),
                (
                    "request_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("expected_admission_date", models.DateField(blank=True, null=True)),
                ("expected_stay_days", models.PositiveIntegerField(default=1)),
                ("primary_diagnosis", models.CharField(max_length=300)),
                ("treatment_plan", models.TextField()),
                (
                    "requested_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "tpa_reference",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="TPA-assigned reference / pre-auth number",
                        max_length=50,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("decision_at", models.DateTimeField(blank=True, null=True)),
                ("decision_notes", models.TextField(blank=True, default="")),
                ("valid_until", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "admission",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pre_auths",
                        to="ipd.admission",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pre_auths",
                        to="core.hospital",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pre_auths",
                        to="core.patient",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pre_auths",
                        to="insurance.policycoverage",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pre_auths_requested",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-request_date"],
            },
        ),
        migrations.AddField(
            model_name="claim",
            name="pre_auth",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="claims",
                to="insurance.preauth",
            ),
        ),
        migrations.CreateModel(
            name="TPA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=20)),
                ("name", models.CharField(max_length=200)),
                ("short_name", models.CharField(blank=True, default="", max_length=50)),
                (
                    "contact_person",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.TextField(blank=True, default="")),
                ("portal_url", models.URLField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tpas",
                        to="core.hospital",
                    ),
                ),
                (
                    "insurance_companies",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Insurers this TPA administers",
                        related_name="tpas",
                        to="insurance.insurancecompany",
                    ),
                ),
            ],
            options={
                "verbose_name": "TPA",
                "verbose_name_plural": "TPAs",
                "ordering": ["name"],
                "unique_together": {("hospital", "code")},
            },
        ),
        migrations.AddField(
            model_name="policycoverage",
            name="tpa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="policies",
                to="insurance.tpa",
            ),
        ),
    ]
