# Generated by Django 5.1.4 on 2026-05-25 12:53

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0002_invoice_amount_refunded_alter_invoice_code_and_more'),
        ('core', '0001_initial'),
        ('department', '0001_initial'),
        ('ipd', '0001_initial'),
        ('specialist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donation_id', models.CharField(db_index=True, help_text='Auto-generated, e.g. DON-20260508-0001', max_length=30, unique=True)),
                ('donation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('volume_collected_ml', models.PositiveIntegerField(default=350, help_text='Standard whole blood collection: 350-450 ml')),
                ('blood_group', models.CharField(choices=[('A_POS', 'A+'), ('A_NEG', 'A-'), ('B_POS', 'B+'), ('B_NEG', 'B-'), ('AB_POS', 'AB+'), ('AB_NEG', 'AB-'), ('O_POS', 'O+'), ('O_NEG', 'O-')], help_text="Should match donor's group; verified at collection", max_length=10)),
                ('pre_hb_g_dl', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Hb level g/dL — must be ≥ 12.5 (M) or ≥ 12.0 (F)', max_digits=4)),
                ('pre_bp_systolic', models.PositiveIntegerField(default=0)),
                ('pre_bp_diastolic', models.PositiveIntegerField(default=0)),
                ('pre_pulse', models.PositiveIntegerField(default=0)),
                ('pre_temperature_c', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=4)),
                ('test_hiv', models.CharField(choices=[('PENDING', 'Pending'), ('NEGATIVE', 'Negative (Pass)'), ('POSITIVE', 'Positive (Fail)')], default='PENDING', max_length=10)),
                ('test_hbsag', models.CharField(choices=[('PENDING', 'Pending'), ('NEGATIVE', 'Negative (Pass)'), ('POSITIVE', 'Positive (Fail)')], default='PENDING', max_length=10)),
                ('test_hcv', models.CharField(choices=[('PENDING', 'Pending'), ('NEGATIVE', 'Negative (Pass)'), ('POSITIVE', 'Positive (Fail)')], default='PENDING', max_length=10)),
                ('test_syphilis', models.CharField(choices=[('PENDING', 'Pending'), ('NEGATIVE', 'Negative (Pass)'), ('POSITIVE', 'Positive (Fail)')], default='PENDING', max_length=10)),
                ('test_malaria', models.CharField(choices=[('PENDING', 'Pending'), ('NEGATIVE', 'Negative (Pass)'), ('POSITIVE', 'Positive (Fail)')], default='PENDING', max_length=10)),
                ('screening_completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('COLLECTED', 'Collected, awaiting screening'), ('SCREENING', 'Screening in progress'), ('PASSED', 'Screening passed — bags created'), ('FAILED', 'Screening failed — discarded'), ('DISCARDED', 'Manually discarded')], default='COLLECTED', max_length=15)),
                ('discard_reason', models.CharField(blank=True, default='', max_length=300)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_donations', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_donations', to='core.hospital')),
                ('screened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screened_donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-donation_date'],
            },
        ),
        migrations.CreateModel(
            name='BloodBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bag_id', models.CharField(db_index=True, help_text='Auto-generated, e.g. BB-20260508-0001', max_length=30, unique=True)),
                ('component', models.CharField(choices=[('WHOLE', 'Whole Blood'), ('PRBC', 'Packed Red Blood Cells'), ('FFP', 'Fresh Frozen Plasma'), ('PLATELETS', 'Platelets'), ('CRYO', 'Cryoprecipitate')], default='WHOLE', max_length=15)),
                ('blood_group', models.CharField(choices=[('A_POS', 'A+'), ('A_NEG', 'A-'), ('B_POS', 'B+'), ('B_NEG', 'B-'), ('AB_POS', 'AB+'), ('AB_NEG', 'AB-'), ('O_POS', 'O+'), ('O_NEG', 'O-')], db_index=True, max_length=10)),
                ('volume_ml', models.PositiveIntegerField(default=350)),
                ('collected_at', models.DateTimeField()),
                ('expiry_date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('QUARANTINE', 'Quarantine (awaiting clearance)'), ('AVAILABLE', 'Available for issue'), ('RESERVED', 'Reserved (cross-matched)'), ('ISSUED', 'Issued'), ('EXPIRED', 'Expired'), ('DISCARDED', 'Discarded')], db_index=True, default='QUARANTINE', max_length=15)),
                ('storage_location', models.CharField(blank=True, default='', help_text="e.g. 'Fridge A1, Shelf 3', 'Freezer B'", max_length=80)),
                ('discard_reason', models.CharField(blank=True, default='', max_length=300)),
                ('discarded_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discarded_bags', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_bags', to='core.hospital')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bags', to='blood_bank.blooddonation')),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donor_id', models.CharField(db_index=True, help_text='Auto-generated, e.g. BD-20260508-0001', max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(blank=True, default='', max_length=80)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('dob', models.DateField()),
                ('blood_group', models.CharField(choices=[('A_POS', 'A+'), ('A_NEG', 'A-'), ('B_POS', 'B+'), ('B_NEG', 'B-'), ('AB_POS', 'AB+'), ('AB_NEG', 'AB-'), ('O_POS', 'O+'), ('O_NEG', 'O-')], db_index=True, max_length=10)),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.CharField(blank=True, default='', max_length=300)),
                ('aadhaar_last4', models.CharField(blank=True, default='', max_length=4)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('is_eligible', models.BooleanField(default=True, help_text='Cleared for donation by medical officer')),
                ('deferral_until', models.DateField(blank=True, help_text='Temporary deferral end date (e.g. recent illness)', null=True)),
                ('deferral_reason', models.CharField(blank=True, default='', max_length=300)),
                ('donor_type', models.CharField(choices=[('VOLUNTARY', 'Voluntary'), ('REPLACEMENT', 'Replacement (for a patient)'), ('AUTOLOGOUS', 'Autologous (for self)'), ('DIRECTED', 'Directed (specific recipient)')], default='VOLUNTARY', max_length=15)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('total_donations', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_donors', to='core.hospital')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='donations', to='blood_bank.blooddonor'),
        ),
        migrations.CreateModel(
            name='BloodRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Auto-generated, e.g. BR-20260508-0001', max_length=30, unique=True)),
                ('blood_group', models.CharField(choices=[('A_POS', 'A+'), ('A_NEG', 'A-'), ('B_POS', 'B+'), ('B_NEG', 'B-'), ('AB_POS', 'AB+'), ('AB_NEG', 'AB-'), ('O_POS', 'O+'), ('O_NEG', 'O-')], help_text="Patient's blood group (to find compatible donor groups)", max_length=10)),
                ('component', models.CharField(choices=[('WHOLE', 'Whole Blood'), ('PRBC', 'Packed Red Blood Cells'), ('FFP', 'Fresh Frozen Plasma'), ('PLATELETS', 'Platelets'), ('CRYO', 'Cryoprecipitate')], default='PRBC', max_length=15)),
                ('units_required', models.PositiveIntegerField(default=1)),
                ('urgency', models.CharField(choices=[('ROUTINE', 'Routine'), ('URGENT', 'Urgent (within 24h)'), ('EMERGENCY', 'Emergency (immediate)')], default='ROUTINE', max_length=12)),
                ('purpose', models.CharField(help_text="Clinical indication, e.g. 'Severe anaemia, Hb 6.2'", max_length=300)),
                ('status', models.CharField(choices=[('PENDING', 'Pending review'), ('CROSSMATCH', 'Cross-matching in progress'), ('RESERVED', 'Bag(s) reserved'), ('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('rejection_reason', models.CharField(blank=True, default='', max_length=300)),
                ('cancelled_reason', models.CharField(blank=True, default='', max_length=300)),
                ('requested_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_requisitions', to='ipd.admission')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_requisitions', to='department.department')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requisitions', to='core.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blood_requisitions', to='core.patient')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blood_requisitions', to='specialist.doctor')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='BloodIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_to_dept', models.CharField(blank=True, default='', help_text="e.g. 'ICU', 'OT-2', 'Ward 3B'", max_length=80)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_by_name', models.CharField(blank=True, default='', help_text='Name of nurse/staff receiving the bag', max_length=120)),
                ('transfusion_started_at', models.DateTimeField(blank=True, null=True)),
                ('transfusion_completed_at', models.DateTimeField(blank=True, null=True)),
                ('reactions_observed', models.TextField(blank=True, default='')),
                ('bag_returned', models.BooleanField(default=False, help_text='True if bag returned unused / partial')),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bag', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='issue', to='blood_bank.bloodbag')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_issues', to='billing.invoice')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bags_issued', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='blood_bank.bloodrequisition')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddField(
            model_name='bloodbag',
            name='issued_to_requisition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_bags', to='blood_bank.bloodrequisition'),
        ),
        migrations.CreateModel(
            name='CrossMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('PENDING', 'Pending'), ('COMPATIBLE', 'Compatible'), ('INCOMPATIBLE', 'Incompatible')], default='PENDING', max_length=15)),
                ('notes', models.CharField(blank=True, default='', max_length=300)),
                ('performed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossmatches', to='blood_bank.bloodbag')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crossmatches_performed', to=settings.AUTH_USER_MODEL)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crossmatches', to='blood_bank.bloodrequisition')),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='blooddonor',
            index=models.Index(fields=['blood_group'], name='blood_bank__blood_g_efd0af_idx'),
        ),
        migrations.AddIndex(
            model_name='blooddonor',
            index=models.Index(fields=['phone'], name='blood_bank__phone_73699e_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodrequisition',
            index=models.Index(fields=['status', 'urgency'], name='blood_bank__status_3ad88d_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodbag',
            index=models.Index(fields=['status', 'blood_group', 'component'], name='blood_bank__status_3dbc94_idx'),
        ),
        migrations.AddIndex(
            model_name='bloodbag',
            index=models.Index(fields=['expiry_date'], name='blood_bank__expiry__86c35c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='crossmatch',
            unique_together={('requisition', 'bag')},
        ),
    ]
