# Generated by Django 5.1.4 on 2026-05-08 10:53

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("billing", "0002_invoice_amount_refunded_alter_invoice_code_and_more"),
        ("core", "0001_initial"),
        ("department", "0001_initial"),
        ("specialist", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Admission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Auto e.g. IPD-20260507-0001",
                        max_length=20,
                    ),
                ),
                (
                    "admission_type",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("EMERGENCY", "Emergency"),
                            ("REFERRAL", "Referral"),
                            ("MATERNITY", "Maternity"),
                        ],
                        default="PLANNED",
                        max_length=12,
                    ),
                ),
                (
                    "admission_diagnosis",
                    models.TextField(
                        help_text="Provisional diagnosis at admission. Will be refined at discharge."
                    ),
                ),
                ("admission_notes", models.TextField(blank=True)),
                ("chief_complaint", models.CharField(blank=True, max_length=300)),
                (
                    "admitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("expected_discharge_date", models.DateField(blank=True, null=True)),
                ("discharged_at", models.DateTimeField(blank=True, null=True)),
                (
                    "discharge_type",
                    models.CharField(
                        blank=True,
                        help_text="ROUTINE / DAMA / TRANSFER / EXPIRED — set at discharge",
                        max_length=15,
                    ),
                ),
                (
                    "locked_bed_rent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Bed rent at time of admission. Charges accrue at this rate.",
                        max_digits=10,
                    ),
                ),
                (
                    "locked_nursing_charge",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "locked_gst_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ADMITTED", "Admitted (in-patient)"),
                            ("DISCHARGED", "Discharged"),
                            ("ABSCONDED", "Absconded"),
                            ("DAMA", "DAMA (discharge against medical advice)"),
                            ("EXPIRED", "Expired"),
                            ("TRANSFERRED", "Transferred out"),
                            ("CANCELLED", "Cancelled (admission void)"),
                        ],
                        db_index=True,
                        default="ADMITTED",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "attending_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ipd_admissions",
                        to="specialist.doctor",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ipd_admissions",
                        to="department.department",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "invoice",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ipd_admission",
                        to="billing.invoice",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admissions",
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-admitted_at"],
            },
        ),
        migrations.CreateModel(
            name="AdmissionService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "description",
                    models.CharField(
                        help_text="Free-text description if no catalog entry",
                        max_length=200,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1"), max_digits=8
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("18.00"), max_digits=5
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "gst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "service_date",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=300)),
                (
                    "admission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="ipd.admission",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="billing.servicecatalog",
                    ),
                ),
            ],
            options={
                "ordering": ["admission", "service_date"],
            },
        ),
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "label",
                    models.CharField(
                        help_text="Bed label within the room, e.g. 'A', 'B', '1', '2'",
                        max_length=10,
                    ),
                ),
                (
                    "bed_rent",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Per-day bed rent (₹). Defaults from ward.default_bed_rent.",
                        max_digits=10,
                    ),
                ),
                (
                    "nursing_charge",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Per-day nursing care charge.",
                        max_digits=10,
                    ),
                ),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("OCCUPIED", "Occupied"),
                            ("RESERVED", "Reserved (cleaning/admission pending)"),
                            ("MAINTENANCE", "Maintenance / out of service"),
                        ],
                        db_index=True,
                        default="AVAILABLE",
                        max_length=12,
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["room", "label"],
            },
        ),
        migrations.AddField(
            model_name="admission",
            name="bed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="admissions",
                to="ipd.bed",
            ),
        ),
        migrations.CreateModel(
            name="DailyCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "charge_date",
                    models.DateField(
                        db_index=True,
                        help_text="Calendar date this charge represents (one row per stay-day)",
                    ),
                ),
                (
                    "bed_rent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "nursing_charge",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "other_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Equipment / monitoring / oxygen / other per-day line items",
                        max_digits=10,
                    ),
                ),
                ("other_description", models.CharField(blank=True, max_length=200)),
                (
                    "gst_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "gst_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "admission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_charges",
                        to="ipd.admission",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["admission", "charge_date"],
            },
        ),
        migrations.CreateModel(
            name="DischargeSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "final_diagnosis",
                    models.TextField(
                        help_text="Confirmed/refined diagnosis at discharge"
                    ),
                ),
                (
                    "course_in_hospital",
                    models.TextField(
                        help_text="Narrative of investigations, treatment, response"
                    ),
                ),
                (
                    "procedures_done",
                    models.TextField(
                        blank=True,
                        help_text="Surgeries / procedures performed during the stay",
                    ),
                ),
                (
                    "treatment_given",
                    models.TextField(
                        blank=True,
                        help_text="Major medications / IV / interventions during the stay",
                    ),
                ),
                (
                    "investigations_summary",
                    models.TextField(
                        blank=True,
                        help_text="Key lab/imaging findings to highlight on discharge",
                    ),
                ),
                (
                    "condition_at_discharge",
                    models.CharField(
                        blank=True,
                        help_text="Vitals + general condition at discharge",
                        max_length=300,
                    ),
                ),
                (
                    "discharge_advice",
                    models.TextField(
                        blank=True,
                        help_text="Wound care, lifestyle, diet, activity restrictions",
                    ),
                ),
                (
                    "medications_on_discharge",
                    models.TextField(
                        blank=True,
                        help_text="Drugs to continue at home, with frequency + duration",
                    ),
                ),
                (
                    "follow_up_advice",
                    models.CharField(
                        blank=True,
                        help_text="When/where to follow up (e.g. 'OPD after 7 days')",
                        max_length=300,
                    ),
                ),
                (
                    "prepared_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "finalized_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set when the doctor signs off — locks the document",
                        null=True,
                    ),
                ),
                (
                    "admission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discharge_summary",
                        to="ipd.admission",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
                (
                    "prepared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="prepared_discharge_summaries",
                        to="specialist.doctor",
                    ),
                ),
            ],
            options={
                "ordering": ["-prepared_at"],
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "number",
                    models.CharField(
                        help_text="Room number, e.g. '201', 'ICU-3'", max_length=20
                    ),
                ),
                (
                    "is_ac",
                    models.BooleanField(default=False, help_text="Air-conditioned"),
                ),
                ("has_attached_bath", models.BooleanField(default=True)),
                ("notes", models.CharField(blank=True, max_length=200)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["ward", "number"],
            },
        ),
        migrations.AddField(
            model_name="bed",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beds",
                to="ipd.room",
            ),
        ),
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Short code, e.g. 'GEN', 'ICU', 'MAT'",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Display name, e.g. 'General Ward — Block A'",
                        max_length=80,
                    ),
                ),
                (
                    "ward_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "General Ward"),
                            ("PRIVATE", "Private / Deluxe"),
                            ("SEMI_PRIVATE", "Semi-Private"),
                            ("ICU", "Intensive Care Unit"),
                            ("HDU", "High Dependency Unit"),
                            ("MATERNITY", "Maternity Ward"),
                            ("PAEDIATRIC", "Paediatric Ward"),
                            ("ISOLATION", "Isolation"),
                            ("DAY_CARE", "Day Care"),
                        ],
                        default="GENERAL",
                        max_length=15,
                    ),
                ),
                (
                    "floor",
                    models.CharField(
                        blank=True,
                        help_text="e.g. 'Ground floor', '2nd floor'",
                        max_length=20,
                    ),
                ),
                (
                    "default_bed_rent",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("500.00"),
                        help_text="Per-day bed rent (₹) — default for beds in this ward",
                        max_digits=10,
                    ),
                ),
                (
                    "default_nursing_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("200.00"),
                        help_text="Per-day nursing care charge",
                        max_digits=10,
                    ),
                ),
                (
                    "default_gst_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="GST on bed rent. India: 0% if rate ≤ ₹1000/day, 5% if ≤ ₹7500, 12% if higher",
                        max_digits=5,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["ward_type", "name"],
            },
        ),
        migrations.AddField(
            model_name="room",
            name="ward",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="ipd.ward",
            ),
        ),
        migrations.AddIndex(
            model_name="admission",
            index=models.Index(
                fields=["patient", "-admitted_at"],
                name="ipd_admissi_patient_38b269_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="admission",
            index=models.Index(
                fields=["status", "-admitted_at"], name="ipd_admissi_status_9545fa_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="admission",
            index=models.Index(
                fields=["attending_doctor", "-admitted_at"],
                name="ipd_admissi_attendi_be4e10_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="admission",
            unique_together={("hospital", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="dailycharge",
            unique_together={("admission", "charge_date")},
        ),
        migrations.AddIndex(
            model_name="bed",
            index=models.Index(fields=["status"], name="ipd_bed_status_4c3faa_idx"),
        ),
        migrations.AddIndex(
            model_name="bed",
            index=models.Index(
                fields=["room", "status"], name="ipd_bed_room_id_85ee06_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="bed",
            unique_together={("hospital", "room", "label")},
        ),
        migrations.AddIndex(
            model_name="ward",
            index=models.Index(
                fields=["ward_type", "is_active"], name="ipd_ward_ward_ty_109893_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ward",
            unique_together={("hospital", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="room",
            unique_together={("hospital", "ward", "number")},
        ),
    ]
