# Generated by Django 5.1.4 on 2026-05-08 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        ("specialist", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique short code, e.g. CARDIO, PHARM, RADIO",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("CLINICAL", "Clinical (sees patients)"),
                            ("DIAGNOSTIC", "Diagnostic (lab, imaging)"),
                            ("PHARMACY", "Pharmacy"),
                            ("WARD", "Ward / IPD"),
                            ("OT", "Operation Theatre"),
                            ("ADMIN", "Administrative"),
                            ("SUPPORT", "Support (housekeeping, security, etc.)"),
                        ],
                        default="CLINICAL",
                        max_length=12,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "location_hint",
                    models.CharField(
                        blank=True, help_text="e.g. 2nd floor, Block-A", max_length=100
                    ),
                ),
                ("phone_extn", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "head_doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="headed_departments",
                        to="specialist.doctor",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="core.hospital",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["type", "is_active"], name="department__type_7a2b2b_idx"
                    )
                ],
                "unique_together": {("hospital", "code")},
            },
        ),
    ]
