# Generated by Django 5.2.14 on 2026-05-26 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('ipd', '0001_initial'),
        ('opd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('scheduled_at', models.DateTimeField(db_index=True, help_text='When this dose was due, per the prescription frequency.')),
                ('administered_at', models.DateTimeField(blank=True, help_text='When the dose was actually given. Null until status moves from SCHEDULED to GIVEN.', null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled (not yet due / not yet administered)'), ('GIVEN', 'Given'), ('REFUSED', 'Refused by patient'), ('MISSED', 'Missed (not administered, no specific reason)'), ('HELD', "Held (per doctor's order)"), ('NPO', 'Patient NPO (nil per os — cannot take orally)'), ('OMITTED', 'Omitted (intentionally skipped)')], db_index=True, default='SCHEDULED', max_length=12)),
                ('actual_dose', models.CharField(blank=True, default='', help_text='If the actual dose differed from prescription, record here.', max_length=50)),
                ('site', models.CharField(blank=True, default='', help_text='For injections: left deltoid, right gluteal, etc.', max_length=50)),
                ('reason', models.CharField(blank=True, default='', help_text='Required when status != GIVEN.', max_length=300)),
                ('response_note', models.CharField(blank=True, default='', help_text="Optional: 'tolerated well', 'mild nausea after dose', etc.", max_length=300)),
                ('administered_by', models.ForeignKey(blank=True, help_text='The nurse who administered (or marked the status). Null while scheduled, populated when the status moves off SCHEDULED.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administered_doses', to=settings.AUTH_USER_MODEL)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_administrations', to='ipd.admission')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hospital')),
                ('prescription_item', models.ForeignKey(help_text='The specific prescription line being administered.', on_delete=django.db.models.deletion.PROTECT, related_name='administrations', to='opd.prescriptionitem')),
            ],
            options={
                'ordering': ['-scheduled_at'],
                'indexes': [models.Index(fields=['admission', '-scheduled_at'], name='nursing_med_admissi_967d06_idx'), models.Index(fields=['status', '-scheduled_at'], name='nursing_med_status_bad88d_idx')],
            },
        ),
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('note_type', models.CharField(choices=[('PROGRESS', 'Progress Note'), ('ASSESSMENT', 'Nursing Assessment'), ('INTERVENTION', 'Nursing Intervention'), ('EVALUATION', 'Evaluation / Patient Response'), ('INCIDENT', 'Incident / Adverse Event'), ('EDUCATION', 'Patient/Family Education'), ('OTHER', 'Other')], db_index=True, default='PROGRESS', max_length=15)),
                ('shift', models.CharField(choices=[('MORNING', 'Morning (07:00-15:00)'), ('EVENING', 'Evening (15:00-23:00)'), ('NIGHT', 'Night (23:00-07:00)')], db_index=True, help_text='Which shift this note was written on.', max_length=10)),
                ('content', models.TextField(help_text='The note text. SOAPIE / SBAR style encouraged but not enforced.')),
                ('noted_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When this note was recorded in HMS (not the bedside time, which is in the content if needed).')),
                ('admission', models.ForeignKey(help_text='The admission this note belongs to. Required.', on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to='ipd.admission')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hospital')),
                ('nurse', models.ForeignKey(help_text='The nurse who wrote this note. Should match request.user normally.', on_delete=django.db.models.deletion.PROTECT, related_name='nursing_notes_authored', to=settings.AUTH_USER_MODEL)),
                ('parent_note', models.ForeignKey(blank=True, help_text='Set if this note is an addendum to an earlier note. Addenda cannot be deleted; original cannot be edited.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addenda', to='nursing.nursingnote')),
            ],
            options={
                'ordering': ['-noted_at'],
                'indexes': [models.Index(fields=['admission', '-noted_at'], name='nursing_nur_admissi_cd258b_idx'), models.Index(fields=['shift', '-noted_at'], name='nursing_nur_shift_a8879b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ShiftHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('shift_date', models.DateField(db_index=True, help_text='The date this handover happened.')),
                ('outgoing_shift', models.CharField(choices=[('MORNING', 'Morning'), ('EVENING', 'Evening'), ('NIGHT', 'Night')], db_index=True, help_text="The shift that's ENDING.", max_length=10)),
                ('priority', models.CharField(choices=[('ROUTINE', 'Routine'), ('WATCH', 'Watch closely'), ('CRITICAL', 'Critical — check immediately')], db_index=True, default='ROUTINE', max_length=10)),
                ('summary', models.TextField(help_text='Narrative summary: condition, pending tasks, watch-for items.')),
                ('pending_tasks', models.TextField(blank=True, default='', help_text='Bullet list of things the incoming shift must do (med due, dressing change, etc.).')),
                ('acknowledged_at', models.DateTimeField(blank=True, help_text='When the incoming nurse acknowledged this handover. Null until acknowledged.', null=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='ipd.admission')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.hospital')),
                ('incoming_nurse', models.ForeignKey(blank=True, help_text='Null until the incoming nurse acknowledges. Acknowledgment is via the /acknowledge/ action.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handovers_received', to=settings.AUTH_USER_MODEL)),
                ('outgoing_nurse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shift_date', '-created_at'],
                'indexes': [models.Index(fields=['shift_date', 'outgoing_shift'], name='nursing_shi_shift_d_05c081_idx'), models.Index(fields=['priority', 'shift_date'], name='nursing_shi_priorit_816707_idx')],
                'unique_together': {('admission', 'shift_date', 'outgoing_shift')},
            },
        ),
    ]
